/*
 *  rc_ignition.c
 *
 *  This is a part of a RapidControl SDK source code library.
 *
 *  Copyright (C) 2001 WindRiver Systems.
 *  All rights reserved.
 *  Version 3.30
 *
 */


/* WARNING:  This file is generated by a RapidControl Integration
 * Tool.  Any changes made to this file may be overwritten by
 * subsequent uses of the tool. */

#include "rc.h"
#include "rc_ignition.h"

#ifdef __SNMP_API_ENABLED__
#include "rcm_mibsrch.h"
#endif

#include "vd_glue.h"
#include "vd_glue_basic.h"
#include "vd_glue_struct.h"
#include "vd_glue_table.h"

/* Access Options Structure */ 
static DTEnumInfo mAccessTbl[] =
{
    {"ENABLE",ENUM_ACCESS_ENABLE,0},
    {"CONFIG",ENUM_ACCESS_CONFIG,0},
    {"SUPER",ENUM_ACCESS_SUPER,0}
};

DTTypeInfo mAccessInfo =
{	NULL,
	NULL,
	kDTaccess,
	"N=3 D=|",
	0,
	NULL,
	NULL,
	mAccessTbl
};



#define RLI_OFFSET(STRUCTURE, FIELD)    (Counter)&(((STRUCTURE *)NULL)->FIELD)

StrcDes *Ignite_DB1(StrcDes *pCurrStruct)
{
    StrcDes *p_sdrStructDes = pCurrStruct;

    DB_CreateEntry("gPortNo", NULL, kDTuinteger, kReadWriteAccess, 0, 0, NULL, VD_ReadPortNo, VD_WritePortNo, NULL, 0);
	DB_CreateEntry("gDomainID", NULL, kDTuinteger, kReadWriteAccess, 0, 0, NULL, VD_ReadDomainID, VD_WriteDomainID, NULL, 0);
    return p_sdrStructDes;
}


extern void Ignite_Database(void)
{
    StrcDes *p_sdrStructDes;

    p_sdrStructDes = Ignite_DB1(NULL);


    return;
}
