/*
 *  rc_options.h
 *
 *  This is a part of the RapidControl SDK source code library.
 *
 *  Copyright (C) 2001 Wind River, Inc.
 *  All rights reserved.
 *  Version 3.30
 *
 */

/* WARNING:  This file is generated by a RapidControl Integration
 * tool.  Any changes made to this file may be overwritten by
 * subsequent uses of the tool. */


#ifndef __OPTIONS_HEADER__
#define __OPTIONS_HEADER__

/*-----------------------------------------------------------------------*/
/* System Specification */


/* Host Operating System */
#define	__FreeRTOS_OS__
#undef	__VXWORKS_OS__
#undef	__PSOS_OS__
#undef	__VRTX_OS__
#undef	__WIN32_OS__
#undef	__POSIX_OS__
#undef	__NUCLEUS_OS__
#undef	__CHORUS_OS__


/* Compiler Specific Type Definitions */
/* Signed Quantities */
typedef	char	sbyte;
typedef	short	sbyte2;
typedef	int	sbyte4;

/* Unsigned Quantities */
typedef	unsigned char	ubyte;
typedef	unsigned short	ubyte2;
typedef	unsigned int	ubyte4;


/* N.B. Some compilers don't allow global arrays to be initialized 
 * to values other than zero.  If that's the case, then tables, 
 * such as the simple array for the RapidMark Host Database,  
 * aren't allowed as an option. */
#define	__TABLES_ALLOWED__


/* In case a compiler (like Metrowerks) pre #defines Boolean types. */
#undef	__BOOLEAN_DEFINED__


/* These flags let the RapidControl System know about the endian-ness 
 * of the underlying processor. */
#define	__LITTLE_ENDIAN_SYSTEM__
#undef	__BIG_ENDIAN_SYSTEM__


/* Number of Real-Time Clock Ticks (which cause Processor
 * Interrupts ) per Second */
#define	kHwTicksPerSecond	1000


/*-----------------------------------------------------------------------*/
/* General Configuration */


/* On-line Database Structure for OCB. */
#undef	__DATABASE_USE_ARRAY__
#define	__DATABASE_USE_HASH__
#undef	__DATABASE_USE_BTREE__


/* The amount of memory that is allocated by RapidControl to 
 * make appropriate data substitutions. This value should be 
 * equal to largest size of data, in bytes, that can be  
 * substituted for a RapidMark. */
#define	kMagicMarkupBufferSize	1024

/* RapidMark delimiters */
#define	kMagicMarkupStartChar0	'['
#define	kMagicMarkupStartChar1	'['
#define	kMagicMarkupEndChar0	']'
#define	kMagicMarkupEndChar1	']'


/* Each socket used by RapidControl must have a timeout mechanism, 
 * in order to tear down any obsolete connections. */
#define	kSocketTimeOut	30


/* The Port Number which is used by the embedded HTTP Server. */
#define	kHTTP_FIXED_PORT	80


/* The following flags determine whether the server is running 
 * in single threaded or multithreaded mode, and the number of HTTP
 * requests that can be serviced at any one time. */
#undef	__SINGLE_THREADED_SERVER_ENABLED__
#define	__MULTI_THREADED_SERVER_ENABLED__
#define	kHTTPD_QUEUE_SIZE	2


/* Memory Management -- does MALLOC and FREE ( see memmgr.c )
 * map to the device OS malloc and free routines, or do they  
 * access RapidControl's own memory management? */
#define	__OS_MALLOC_PROVIDED__
#undef	kInitialMemoryAllocation


/* IP Filtering allows you to block access to your device based on the
 * client IP address.  Typically, this feature has been used to allow only
 * local (i.e. LAN-based) access to the device. */
#undef	__ENABLE_LAN_IP_FILTER__
#undef	RLI_CUSTOM_DYNAMIC_IP_FILTER_ENABLED
#undef	RLI_CUSTOM_DYNAMIC_IP_CHECK


/* Do the RapidMarks make use of the SNMP APIs used by an 
 * SNMP agent?  */
#undef	__SNMP_API_ENABLED__

#undef	__NO_SNMP_STACK__
#undef	__EPILOGUE_ENVOY_SNMP_STACK__
#undef	__EPILOGUE_ENVOY_MASTER_SUBAGENT_SNMP_STACK__
#undef	__WINDNET_SNMP_BINARY__
#undef	__WINDNET_SNMP_SOURCE__
#undef	__GENERIC_SNMP_V1__
#undef	__CMU_SNMP_V1__
#undef	__OTHER_SNMP_STACK__


/* The external API function allows the RapidControl Backplane to 
 * pass RapidMarks, which aren't located in the OCB database, onto 
 * a special handling routine.  This is used for both SNMP APIs and 
 * custom data access. */
#undef	__ENABLE_EXTERNAL_API__
#undef	CUSTOM_EXTERNAL_HANDLER


/* Disable Structures turns off RapidControl support for structured data, 
 * specifically the Cache System and the Repeat Macro. This can substantially
 * reduce the total size of the image, but at a loss of functionality. */
#undef	__DISABLE_STRUCTURES__


/* This compiler flag allows the developer to specify whether he/she wants
 * to use the RapidControl library of standard functions (strchr, strlen, etc.),
 * or the system library, if it exists. */
#undef	__USE_LOCAL_ANSI_LIB__


/* The following items describe the Access control model. It has two optional 
 * parts, that being a permision level (which the user must have an equal or 
 * greater level), and an access options list (which -if not zero- the user 
 * must overlap with). */
#define	__RLI_ACCESS_LEVEL_MAXSTR__	"255"
#define	__RLI_ACCESS_LEVEL_MASK__	0x000ff
#define	__RLI_ACCESS_OPTION_MASK__	0x0ff00
#define	__RLI_ACCESS_LEVEL_SHIFT__	8
typedef	sbyte2	Access;

/*-----------------------------------------------------------------------*/
/* The following flag is used to determine the relevant files in 
 * RapidControl for CLI that will be compiled into your project. */

#define	__RCC_ENABLED__


/* Telnet Specifications */
/* Telnet Port */
#define	kRCC_FIXED_PORT	23

#define	kRCC_THREAD_STACK_SIZE	512

/* CLI Task Priority */
#define	kRCC_SERVER_PRIO	3

/* Session Timeout Length */
#define	kRCC_TIMEOUT	180


/* Login Specifications */
#define	kRCC_MAX_LOGIN_ATTEMPTS	3
#define	kRCC_MAX_LOGIN_LEN	16
#define	kRCC_MAX_PASSWORD_LEN	16
#define	kRCC_LOGIN_PROMPT	"Username:"
#define	kRCC_PASSWORD_PROMPT	"Password:"


/* Shell Specifications */
/* Number of Commands in the History Buffer */
#define	kRCC_HISTORY_BUFFER_SIZE	10

/* Prompt Displayed by the Shell */
#define	kRCC_DEFAULT_PROMPT	"OBSwitch"

#define	kRCC_MAX_TOKENS	64
#define	kRCC_ALIAS_BUFFER_SIZE	256
#define	kRCC_ALIAS_COUNT	16


/* Command Specifications */
#define	kRCC_MAX_PROMPT_LEN	64
#define	kRCC_MAX_CMD_LEN	256
#define	kRCC_MAX_PARAMS	16
#define	kOUTPUT_BUFFER_SIZE	kMagicMarkupBufferSize
#define	__RCC_CONSOLE_ENABLED__	


/* System Specifications */
#define	kRCC_MAX_CLI_TASK	1
#undef	__RCC_PARAMETER_ORDER_NONE__
#undef	__RCC_PARAMETER_ORDER_UNNAMED__
#define	__RCC_PARAMETER_ORDER_FULL__


/*-----------------------------------------------------------------------*/
/* Future Extensions */


/* The following items are all used for future enhancements that can be 
 * implemented by "#define"-ing each element as it applies. */
#define __RCC_TUTORIAL__
#define RCC_AUTH_CALLBACK_FN    RCC_TASK_ValidateLogin
//#define __SKIP_LOGIN__
//#define LOGIN_ACCESS_ENABLE


#endif /* __OPTIONS_HEADER__ */


