/*
 *  rcc_cli.h
 *
 *  This is a part of a RapidControl SDK source code library.
 *
 *  Copyright (C) 2001 WindRiver Systems
 *  Version 3.30
 *  All rights reserved.
 *
 */


/* WARNING:  This file will be generated by a RapidControl Integration
 * Tool.  Any changes made to this file may be overwritten by
 * subsequent uses of the tool. */

#ifndef __RCC_CLI_H_HEADER__
#define __RCC_CLI_H_HEADER__

#define mClearCounters_Port            1
#define mConfigBootdelay_Seconds       1
#define mConfigIp_Ip                   1
#define mConfigIp_Netmask              2
#define mConfigIp_Gateway              3
#define mConfigMirrorDestination_port_Port 1
#define mConfigMirrorDestination_port_Direction 2
#define ENUM_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS 1
#define ENMA_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS 0
#define ENUM_CONFIGMIRRORDESTINATION_PORTDIRECTION_EGRESS (ENUM_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS + 1)
#define ENMA_CONFIGMIRRORDESTINATION_PORTDIRECTION_EGRESS 0
#define ENUM_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS_EGRESS (ENUM_CONFIGMIRRORDESTINATION_PORTDIRECTION_EGRESS + 1)
#define ENMA_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS_EGRESS 0
#define mConfigMirrorSource_port_Portlist 1
#define mConfigMirrorSource_port_Direction 2
#define ENUM_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS 1
#define ENMA_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS 0
#define ENUM_CONFIGMIRRORSOURCE_PORTDIRECTION_EGRESS (ENUM_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS + 1)
#define ENMA_CONFIGMIRRORSOURCE_PORTDIRECTION_EGRESS 0
#define ENUM_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS_EGRESS (ENUM_CONFIGMIRRORSOURCE_PORTDIRECTION_EGRESS + 1)
#define ENMA_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS_EGRESS 0
#define mConfigObringDelete_Domain_id  1
#define mConfigObringDomain_id_Domain_id 1
#define mConfigObringDomain_idFail_times_Times 2
#define mConfigObringDomain_idHello_times_Times 2
#define mConfigObringDomain_idPrimary_portEnable_Port 2
#define mConfigObringDomain_idRing_port_Ring_port_1 2
#define mConfigObringDomain_idRing_port_Ring_port_2 3
#define mConfigObringMode_Ring_mode    1
#define ENUM_CONFIGOBRINGMODERING_MODE_PORT_BASED 1
#define ENMA_CONFIGOBRINGMODERING_MODE_PORT_BASED 0
#define ENUM_CONFIGOBRINGMODERING_MODE_VLAN_BASED (ENUM_CONFIGOBRINGMODERING_MODE_PORT_BASED + 1)
#define ENMA_CONFIGOBRINGMODERING_MODE_VLAN_BASED 0
#define mConfigObringNew_Domain_name   1
#define mConfigObringNew_Domain_id     2
#define mConfigObringNew_Node_prio     3
#define ENUM_CONFIGOBRINGNEWNODE_PRIO_HIGH 1
#define ENMA_CONFIGOBRINGNEWNODE_PRIO_HIGH 0
#define ENUM_CONFIGOBRINGNEWNODE_PRIO_MEDIUM (ENUM_CONFIGOBRINGNEWNODE_PRIO_HIGH + 1)
#define ENMA_CONFIGOBRINGNEWNODE_PRIO_MEDIUM 0
#define ENUM_CONFIGOBRINGNEWNODE_PRIO_LOW (ENUM_CONFIGOBRINGNEWNODE_PRIO_MEDIUM + 1)
#define ENMA_CONFIGOBRINGNEWNODE_PRIO_LOW 0
#define mConfigPort_PortNo             1
#define mConfigPortPort_securityAge_time_Age_time 2
#define mConfigPortPort_securityMac_address_Mac_address 2
#define mConfigPortPort_securityMaximum_Maximum 2
#define mConfigSignalChannum_Channum   1
#define mConfigSignalChanparam_Chanid  1
#define mConfigSignalChanparam_EnableQfsdisable 2
#define mConfigSignalChanparam_Alarmtype 3
#define ENUM_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_ENABLE 1
#define ENMA_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_ENABLE 0
#define ENUM_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_DISABLE (ENUM_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_ENABLE + 1)
#define ENMA_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_DISABLE 0
#define ENUM_CONFIGSIGNALCHANPARAMALARMTYPE_CLOSE 1
#define ENMA_CONFIGSIGNALCHANPARAMALARMTYPE_CLOSE 0
#define ENUM_CONFIGSIGNALCHANPARAMALARMTYPE_OPEN (ENUM_CONFIGSIGNALCHANPARAMALARMTYPE_CLOSE + 1)
#define ENMA_CONFIGSIGNALCHANPARAMALARMTYPE_OPEN 0
#define ENUM_CONFIGSIGNALCHANPARAMALARMTYPE_DOWN (ENUM_CONFIGSIGNALCHANPARAMALARMTYPE_OPEN + 1)
#define ENMA_CONFIGSIGNALCHANPARAMALARMTYPE_DOWN 0
#define mConfigSignalJitter_EnableQfsdisable 1
#define mConfigSignalJitter_Time       2
#define ENUM_CONFIGSIGNALJITTERENABLEQFSDISABLE_ENABLE 1
#define ENMA_CONFIGSIGNALJITTERENABLEQFSDISABLE_ENABLE 0
#define ENUM_CONFIGSIGNALJITTERENABLEQFSDISABLE_DISABLE (ENUM_CONFIGSIGNALJITTERENABLEQFSDISABLE_ENABLE + 1)
#define ENMA_CONFIGSIGNALJITTERENABLEQFSDISABLE_DISABLE 0
#define mConfigSignalSampcycle_Time    1
#define mConfigSignalWorkmode_Mode     1
#define mConfigSignalWorkmode_Ip       2
#define mConfigSignalWorkmode_Port     3
#define ENUM_CONFIGSIGNALWORKMODEMODE_UDP 1
#define ENMA_CONFIGSIGNALWORKMODEMODE_UDP 0
#define ENUM_CONFIGSIGNALWORKMODEMODE_TCP (ENUM_CONFIGSIGNALWORKMODEMODE_UDP + 1)
#define ENMA_CONFIGSIGNALWORKMODEMODE_TCP 0
#define mConfigTraffic_statistic_Port_list 1
#define mConfigTrapAdd_TrapType        1
#define ENUM_CONFIGTRAPADDTRAPTYPE_REBOOT 1
#define ENMA_CONFIGTRAPADDTRAPTYPE_REBOOT 0
#define ENUM_CONFIGTRAPADDTRAPTYPE_PORT (ENUM_CONFIGTRAPADDTRAPTYPE_REBOOT + 1)
#define ENMA_CONFIGTRAPADDTRAPTYPE_PORT 0
#define ENUM_CONFIGTRAPADDTRAPTYPE_RING (ENUM_CONFIGTRAPADDTRAPTYPE_PORT + 1)
#define ENMA_CONFIGTRAPADDTRAPTYPE_RING 0
#define ENUM_CONFIGTRAPADDTRAPTYPE_VOL (ENUM_CONFIGTRAPADDTRAPTYPE_RING + 1)
#define ENMA_CONFIGTRAPADDTRAPTYPE_VOL 0
#define ENUM_CONFIGTRAPADDTRAPTYPE_TRAFFIC (ENUM_CONFIGTRAPADDTRAPTYPE_VOL + 1)
#define ENMA_CONFIGTRAPADDTRAPTYPE_TRAFFIC 0
#define mConfigTrapDelete_TrapType     1
#define ENUM_CONFIGTRAPDELETETRAPTYPE_REBOOT 1
#define ENMA_CONFIGTRAPDELETETRAPTYPE_REBOOT 0
#define ENUM_CONFIGTRAPDELETETRAPTYPE_PORT (ENUM_CONFIGTRAPDELETETRAPTYPE_REBOOT + 1)
#define ENMA_CONFIGTRAPDELETETRAPTYPE_PORT 0
#define ENUM_CONFIGTRAPDELETETRAPTYPE_RING (ENUM_CONFIGTRAPDELETETRAPTYPE_PORT + 1)
#define ENMA_CONFIGTRAPDELETETRAPTYPE_RING 0
#define ENUM_CONFIGTRAPDELETETRAPTYPE_VOL (ENUM_CONFIGTRAPDELETETRAPTYPE_RING + 1)
#define ENMA_CONFIGTRAPDELETETRAPTYPE_VOL 0
#define ENUM_CONFIGTRAPDELETETRAPTYPE_TRAFFIC (ENUM_CONFIGTRAPDELETETRAPTYPE_VOL + 1)
#define ENMA_CONFIGTRAPDELETETRAPTYPE_TRAFFIC 0
#define mConfigTrapServer_mac_Mac_addr 1
#define mConfigUserAccess_Name         1
#define mConfigUserAccess_Access       2
#define mConfigUserAdd_Name            1
#define mConfigUserAdd_Access          2
#define mConfigUserDelete_Name         1
#define mConfigUserPassword_NULL1      1
#define mDebugDiag_Board_name          1
#define ENUM_DEBUGDIAGBOARD_NAME_GE22103MA 1
#define ENMA_DEBUGDIAGBOARD_NAME_GE22103MA 0
#define ENUM_DEBUGDIAGBOARD_NAME_GE2C400U (ENUM_DEBUGDIAGBOARD_NAME_GE22103MA + 1)
#define ENMA_DEBUGDIAGBOARD_NAME_GE2C400U 0
#define ENUM_DEBUGDIAGBOARD_NAME_GE1040PU (ENUM_DEBUGDIAGBOARD_NAME_GE2C400U + 1)
#define ENMA_DEBUGDIAGBOARD_NAME_GE1040PU 0
#define mDebugEepromClear_Offset       1
#define mDebugEepromClear_Nbytes       2
#define mDebugEepromDump_Offset        1
#define mDebugEepromDump_Nbytes        2
#define mDebugEepromTest_Offset        1
#define mDebugEepromTest_Nbytes        2
#define mDebugEepromTest_Value         3
#define mDebugLogin_EnableQppdisable   1
#define ENUM_DEBUGLOGINENABLEQPPDISABLE_ENABLE 1
#define ENMA_DEBUGLOGINENABLEQPPDISABLE_ENABLE 0
#define ENUM_DEBUGLOGINENABLEQPPDISABLE_DISABLE (ENUM_DEBUGLOGINENABLEQPPDISABLE_ENABLE + 1)
#define ENMA_DEBUGLOGINENABLEQPPDISABLE_DISABLE 0
#define mDebugModule_AddQppdelQppshow  1
#define mDebugModule_Module            2
#define ENUM_DEBUGMODULEADDQPPDELQPPSHOW_ADD 1
#define ENMA_DEBUGMODULEADDQPPDELQPPSHOW_ADD 0
#define ENUM_DEBUGMODULEADDQPPDELQPPSHOW_DEL (ENUM_DEBUGMODULEADDQPPDELQPPSHOW_ADD + 1)
#define ENMA_DEBUGMODULEADDQPPDELQPPSHOW_DEL 0
#define ENUM_DEBUGMODULEADDQPPDELQPPSHOW_SHOW (ENUM_DEBUGMODULEADDQPPDELQPPSHOW_DEL + 1)
#define ENMA_DEBUGMODULEADDQPPDELQPPSHOW_SHOW 0
#define ENUM_DEBUGMODULEMODULE_NMS     1
#define ENMA_DEBUGMODULEMODULE_NMS     0
#define ENUM_DEBUGMODULEMODULE_OBRING  (ENUM_DEBUGMODULEMODULE_NMS + 1)
#define ENMA_DEBUGMODULEMODULE_OBRING  0
#define ENUM_DEBUGMODULEMODULE_UART    (ENUM_DEBUGMODULEMODULE_OBRING + 1)
#define ENMA_DEBUGMODULEMODULE_UART    0
#define mDebugObringDisable_Ring_index 1
#define mDebugObringEnable_Ring_index  1
#define mDebugObringReboot_Ring_index  1
#define mDebugSwitchGetreg_Page        1
#define mDebugSwitchGetreg_Address     2
#define mDebugSwitchSetreg_Page        1
#define mDebugSwitchSetreg_Address     2
#define mDebugSwitchSetreg_Value       3
#define mExit_All                      1
#define mHelp_Commands                 1
#define mHelp_Edit                     2
#define mPing_Host_ip                  1
#define mShowCounters_Port             1
#define mShowObring_Topo               1
#define mShowRegister_Page             1
#define mShowRegister_Address          2
#define mShowRegister_Lenth            3
#define mShowTask_Runtime              1
#define mShowUart_Port                 1
#define mTftp_Server_ip                1
#define mTftp_GetQppput                2
#define mTftp_Filename                 3
#define ENUM_TFTPGETQPPPUT_GET         1
#define ENMA_TFTPGETQPPPUT_GET         0
#define ENUM_TFTPGETQPPPUT_PUT         (ENUM_TFTPGETQPPPUT_GET + 1)
#define ENMA_TFTPGETQPPPUT_PUT         0
#define mTree__syntax                  1
#endif /* __RCC_CLI_H_HEADER__ */
