/*
 *  rcc_cli.c
 *
 *  This is a part of a RapidControl SDK source code library.
 *
 *  Copyright (C) 2001 WindRiver Systems
 *  Version 3.30
 *  All rights reserved.
 *
 */


/* WARNING:  This file will be generated by a RapidControl Integration
 * Tool.  Any changes made to this file may be overwritten by
 * subsequent uses of the tool. */

#include "rc.h"
#include "rc_ignition.h"
#include "rcc.h"
#include "rcc_cli.h"
#include "rcc_handlers.h"

static DTTypeInfo mClearCounters_PortInfo =
{
    "Logic port number",
    NULL,
    kDTuchar,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mClearCountersParams[] =
{
    { "port", kDTuchar, mClearCounters_Port, 0|kRCC_PARAMETER_NOKEYWORD, &mClearCounters_PortInfo }
};

static paramEntry mClearCountersParamArray[] =
{
    {mClearCounters_Port, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mClearCountersHandlers[] =
{
    { 0, rcc_clear_counters, 1, mClearCountersParamArray }
};

#define kClearCountersHelp "\
Clear port MIB counters\
"

static handlerDefn mClearMac_address_tableHandlers[] =
{
    { 0, rcc_clear_mac_addr_table, 0, NULL }
};

#define kClearMac_address_tableHelp "\
Clear MAC address table\
"

static cmdNode mClearChildren[] =
{ 
    { "counters", kClearCountersHelp, NULL, 0, NULL, 0, 0, NULL, 1, mClearCountersParams, 1, mClearCountersHandlers },
    { "mac-address-table", kClearMac_address_tableHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mClearMac_address_tableHandlers }
};

#define kClearHelp "\
Enter clear commands level\
"

#define kConfigAlarmHelp "\
Alarm configuration\
"

static DTTypeInfo mConfigBootdelay_SecondsInfo =
{
    "Bootdelay time (should be 0-5)",
    NULL,
    kDTuchar,
    "L=0 U=5",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigBootdelayParams[] =
{
    { "seconds", kDTuchar, mConfigBootdelay_Seconds, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigBootdelay_SecondsInfo }
};

static paramEntry mConfigBootdelayParamArray[] =
{
    {mConfigBootdelay_Seconds, kRCC_PARAMETER_OPTIONAL }
};

static handlerDefn mConfigBootdelayHandlers[] =
{
    { 0, rcc_config_bootdelay, 1, mConfigBootdelayParamArray }
};

#define kConfigBootdelayHelp "\
Config the bootdelay time(seconds)\
"

static DTTypeInfo mConfigIp_IpInfo =
{
    "IP address",
    NULL,
    kDTipaddress,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mConfigIp_NetmaskInfo =
{
    "Subnet mask",
    NULL,
    kDTipaddress,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mConfigIp_GatewayInfo =
{
    "Gateway IP",
    NULL,
    kDTipaddress,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigIpParams[] =
{
    { "ip", kDTipaddress, mConfigIp_Ip, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigIp_IpInfo },
    { "netmask", kDTipaddress, mConfigIp_Netmask, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigIp_NetmaskInfo },
    { "gateway", kDTipaddress, mConfigIp_Gateway, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigIp_GatewayInfo }
};

static paramEntry mConfigIpParamArray[] =
{
    {mConfigIp_Ip, kRCC_PARAMETER_REQUIRED },
    {mConfigIp_Netmask, kRCC_PARAMETER_OPTIONAL },
    {mConfigIp_Gateway, kRCC_PARAMETER_OPTIONAL }
};

static handlerDefn mConfigIpHandlers[] =
{
    { 0, rcc_config_ip, 3, mConfigIpParamArray }
};

#define kConfigIpHelp "\
To configure ipaddress/netmask\
"

static DTTypeInfo mConfigMirrorDestination_port_PortInfo =
{
    "Mirror destination port number",
    NULL,
    kDTuinteger,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTEnumInfo mConfigMirrorDestination_port_DirectionTbl[] =
{
    {"ingress",ENUM_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS,ENMA_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS},
    {"egress",ENUM_CONFIGMIRRORDESTINATION_PORTDIRECTION_EGRESS,ENMA_CONFIGMIRRORDESTINATION_PORTDIRECTION_EGRESS},
    {"ingress-egress",ENUM_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS_EGRESS,ENMA_CONFIGMIRRORDESTINATION_PORTDIRECTION_INGRESS_EGRESS}
};

static DTTypeInfo mConfigMirrorDestination_port_DirectionInfo =
{
    "Mirror direction (ingress/egress/ingress-egress)",
    NULL,
    kDTenum,
    "N=3 D=| ",
    0,
    NULL,
    NULL,
    mConfigMirrorDestination_port_DirectionTbl
};

static paramDefn mConfigMirrorDestination_portParams[] =
{
    { "port", kDTuinteger, mConfigMirrorDestination_port_Port, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigMirrorDestination_port_PortInfo },
    { "direction", kDTenum, mConfigMirrorDestination_port_Direction, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigMirrorDestination_port_DirectionInfo }
};

static paramEntry mConfigMirrorDestination_portParamArray[] =
{
    {mConfigMirrorDestination_port_Port, kRCC_PARAMETER_REQUIRED },
    {mConfigMirrorDestination_port_Direction, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigMirrorDestination_portHandlers[] =
{
    { 0, rcc_config_mirror_destination_port, 2, mConfigMirrorDestination_portParamArray }
};

#define kConfigMirrorDestination_portHelp "\
Mirror destination port\
"

static DTTypeInfo mConfigMirrorSource_port_PortlistInfo =
{
    "Mirror source port list",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTEnumInfo mConfigMirrorSource_port_DirectionTbl[] =
{
    {"ingress",ENUM_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS,ENMA_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS},
    {"egress",ENUM_CONFIGMIRRORSOURCE_PORTDIRECTION_EGRESS,ENMA_CONFIGMIRRORSOURCE_PORTDIRECTION_EGRESS},
    {"ingress-egress",ENUM_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS_EGRESS,ENMA_CONFIGMIRRORSOURCE_PORTDIRECTION_INGRESS_EGRESS}
};

static DTTypeInfo mConfigMirrorSource_port_DirectionInfo =
{
    "Mirror direction (ingress/egress/ingress-egress)",
    NULL,
    kDTenum,
    "N=3 D=| ",
    0,
    NULL,
    NULL,
    mConfigMirrorSource_port_DirectionTbl
};

static paramDefn mConfigMirrorSource_portParams[] =
{
    { "portlist", kDTstring, mConfigMirrorSource_port_Portlist, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigMirrorSource_port_PortlistInfo },
    { "direction", kDTenum, mConfigMirrorSource_port_Direction, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigMirrorSource_port_DirectionInfo }
};

static paramEntry mConfigMirrorSource_portParamArray[] =
{
    {mConfigMirrorSource_port_Portlist, kRCC_PARAMETER_REQUIRED },
    {mConfigMirrorSource_port_Direction, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigMirrorSource_portHandlers[] =
{
    { 0, rcc_config_mirror_source_port, 2, mConfigMirrorSource_portParamArray }
};

#define kConfigMirrorSource_portHelp "\
Mirror source port\
"

static cmdNode mConfigMirrorChildren[] =
{ 
    { "destination-port", kConfigMirrorDestination_portHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 2, mConfigMirrorDestination_portParams, 1, mConfigMirrorDestination_portHandlers },
    { "source-port", kConfigMirrorSource_portHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 2, mConfigMirrorSource_portParams, 1, mConfigMirrorSource_portHandlers }
};

#define kConfigMirrorHelp "\
Port mirror configuration\
"

static DTTypeInfo mConfigObringDelete_Domain_idInfo =
{
    "Domain id, Range <1-31>",
    NULL,
    kDTushort,
    "L=1 U=31",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigObringDeleteParams[] =
{
    { "domain_id", kDTushort, mConfigObringDelete_Domain_id, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringDelete_Domain_idInfo }
};

static paramEntry mConfigObringDeleteParamArray[] =
{
    {mConfigObringDelete_Domain_id, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringDeleteHandlers[] =
{
    { 0, rcc_config_obring_delete, 1, mConfigObringDeleteParamArray }
};

#define kConfigObringDeleteHelp "\
Delete OB-Ring domain\
"

static DTTypeInfo mConfigObringDomain_id_Domain_idInfo =
{
    "Domain ID, Range<1-31>",
    NULL,
    kDTuinteger,
    "L=1 U=31",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigObringDomain_idParams[] =
{
    { "domain_id", kDTuinteger, mConfigObringDomain_id_Domain_id, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringDomain_id_Domain_idInfo }
};

static paramEntry mConfigObringDomain_idParamArray[] =
{
    {mConfigObringDomain_id_Domain_id, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringDomain_idHandlers[] =
{
    { 0, rcc_config_obring_domain, 1, mConfigObringDomain_idParamArray }
};

static paramEntry mConfigObringDomain_idEnableParamArray1[] =
{
    {mConfigObringDomain_id_Domain_id, kRCC_PARAMETER_REQUIRED }
};

static paramEntry mConfigObringDomain_idEnableParamArray2[] =
{
    {mConfigObringDomain_id_Domain_id, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringDomain_idEnableHandlers[] =
{
    { 0, rcc_config_obring_enable, 1, mConfigObringDomain_idEnableParamArray1 },
    { kNoHandler, rcc_config_obring_no_enable, 1, mConfigObringDomain_idEnableParamArray2 }
};

#define kConfigObringDomain_idEnableHelp "\
Enable/no enable obring protocol\
"

static DTTypeInfo mConfigObringDomain_idFail_times_TimesInfo =
{
    "Set times, range <3-60> seconds",
    NULL,
    kDTushort,
    "L=3 U=60",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigObringDomain_idFail_timesParams[] =
{
    { "times", kDTushort, mConfigObringDomain_idFail_times_Times, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringDomain_idFail_times_TimesInfo }
};

static paramEntry mConfigObringDomain_idFail_timesParamArray[] =
{
    {mConfigObringDomain_id_Domain_id, kRCC_PARAMETER_REQUIRED },
    {mConfigObringDomain_idFail_times_Times, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringDomain_idFail_timesHandlers[] =
{
    { 0, rcc_config_obring_domain_fail_times, 2, mConfigObringDomain_idFail_timesParamArray }
};

#define kConfigObringDomain_idFail_timesHelp "\
Change fail times\
"

static DTTypeInfo mConfigObringDomain_idHello_times_TimesInfo =
{
    "Set times, range <1-10> seconds",
    NULL,
    kDTushort,
    "L=1 U=10",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigObringDomain_idHello_timesParams[] =
{
    { "times", kDTushort, mConfigObringDomain_idHello_times_Times, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringDomain_idHello_times_TimesInfo }
};

static paramEntry mConfigObringDomain_idHello_timesParamArray[] =
{
    {mConfigObringDomain_id_Domain_id, kRCC_PARAMETER_REQUIRED },
    {mConfigObringDomain_idHello_times_Times, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringDomain_idHello_timesHandlers[] =
{
    { 0, rcc_config_obring_domain_hello_times, 2, mConfigObringDomain_idHello_timesParamArray }
};

#define kConfigObringDomain_idHello_timesHelp "\
Change hello times\
"

static paramEntry mConfigObringDomain_idPrimary_portDisableParamArray[] =
{
    {mConfigObringDomain_id_Domain_id, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringDomain_idPrimary_portDisableHandlers[] =
{
    { 0, rcc_config_obring_domain_primary_port_disable, 1, mConfigObringDomain_idPrimary_portDisableParamArray }
};

#define kConfigObringDomain_idPrimary_portDisableHelp "\
disable primary port function\
"

static DTTypeInfo mConfigObringDomain_idPrimary_portEnable_PortInfo =
{
    "Ring port number",
    NULL,
    kDTuinteger,
    "L=1 U=63",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigObringDomain_idPrimary_portEnableParams[] =
{
    { "port", kDTuinteger, mConfigObringDomain_idPrimary_portEnable_Port, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringDomain_idPrimary_portEnable_PortInfo }
};

static paramEntry mConfigObringDomain_idPrimary_portEnableParamArray[] =
{
    {mConfigObringDomain_id_Domain_id, kRCC_PARAMETER_REQUIRED },
    {mConfigObringDomain_idPrimary_portEnable_Port, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringDomain_idPrimary_portEnableHandlers[] =
{
    { 0, rcc_config_obring_domain_primary_port_enable, 2, mConfigObringDomain_idPrimary_portEnableParamArray }
};

#define kConfigObringDomain_idPrimary_portEnableHelp "\
Enable primary port function\
"

static cmdNode mConfigObringDomain_idPrimary_portChildren[] =
{ 
    { "disable", kConfigObringDomain_idPrimary_portDisableHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mConfigObringDomain_idPrimary_portDisableHandlers },
    { "enable", kConfigObringDomain_idPrimary_portEnableHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigObringDomain_idPrimary_portEnableParams, 1, mConfigObringDomain_idPrimary_portEnableHandlers }
};

#define kConfigObringDomain_idPrimary_portHelp "\
Enable/disable primary port\
"

static DTTypeInfo mConfigObringDomain_idRing_port_Ring_port_1Info =
{
    "Ring port number",
    NULL,
    kDTuinteger,
    "L=1 U=63",
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mConfigObringDomain_idRing_port_Ring_port_2Info =
{
    "Ring port number",
    NULL,
    kDTuinteger,
    "L=1 U=63",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigObringDomain_idRing_portParams[] =
{
    { "ring_port_1", kDTuinteger, mConfigObringDomain_idRing_port_Ring_port_1, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringDomain_idRing_port_Ring_port_1Info },
    { "ring_port_2", kDTuinteger, mConfigObringDomain_idRing_port_Ring_port_2, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringDomain_idRing_port_Ring_port_2Info }
};

static paramEntry mConfigObringDomain_idRing_portParamArray[] =
{
    {mConfigObringDomain_id_Domain_id, kRCC_PARAMETER_REQUIRED },
    {mConfigObringDomain_idRing_port_Ring_port_1, kRCC_PARAMETER_REQUIRED },
    {mConfigObringDomain_idRing_port_Ring_port_2, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringDomain_idRing_portHandlers[] =
{
    { 0, rcc_config_obring_domain_ring_port, 3, mConfigObringDomain_idRing_portParamArray }
};

#define kConfigObringDomain_idRing_portHelp "\
Set ring port\
"

static cmdNode mConfigObringDomain_idChildren[] =
{ 
    { "enable", kConfigObringDomain_idEnableHelp, NULL, kRCC_COMMAND_NO, NULL, 0, 0, NULL, 0, NULL, 2, mConfigObringDomain_idEnableHandlers },
    { "fail-times", kConfigObringDomain_idFail_timesHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigObringDomain_idFail_timesParams, 1, mConfigObringDomain_idFail_timesHandlers },
    { "hello-times", kConfigObringDomain_idHello_timesHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigObringDomain_idHello_timesParams, 1, mConfigObringDomain_idHello_timesHandlers },
    { "primary-port", kConfigObringDomain_idPrimary_portHelp, NULL, 0, NULL, 0, 2, mConfigObringDomain_idPrimary_portChildren, 0, NULL, 0, NULL },
    { "ring-port", kConfigObringDomain_idRing_portHelp, NULL, 0, NULL, 0, 0, NULL, 2, mConfigObringDomain_idRing_portParams, 1, mConfigObringDomain_idRing_portHandlers }
};

#define kConfigObringDomain_idHelp "\
Enter specified domain configuration mode\
"

static DTEnumInfo mConfigObringMode_Ring_modeTbl[] =
{
    {"port-based",ENUM_CONFIGOBRINGMODERING_MODE_PORT_BASED,ENMA_CONFIGOBRINGMODERING_MODE_PORT_BASED},
    {"vlan-based",ENUM_CONFIGOBRINGMODERING_MODE_VLAN_BASED,ENMA_CONFIGOBRINGMODERING_MODE_VLAN_BASED}
};

static DTTypeInfo mConfigObringMode_Ring_modeInfo =
{
    "Ring mode, Enum <port-based, vlan-based>",
    NULL,
    kDTenum,
    "N=2 D=| ",
    0,
    NULL,
    NULL,
    mConfigObringMode_Ring_modeTbl
};

static paramDefn mConfigObringModeParams[] =
{
    { "ring_mode", kDTenum, mConfigObringMode_Ring_mode, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringMode_Ring_modeInfo }
};

static paramEntry mConfigObringModeParamArray[] =
{
    {mConfigObringMode_Ring_mode, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringModeHandlers[] =
{
    { 0, rcc_config_obring_mode, 1, mConfigObringModeParamArray }
};

#define kConfigObringModeHelp "\
Ring mode\
"

static DTTypeInfo mConfigObringNew_Domain_nameInfo =
{
    "OB-Ring domain name, string length less than 8",
    NULL,
    kDTstring,
    "T=AL N=7",
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mConfigObringNew_Domain_idInfo =
{
    "Domain id, Range <1-31>",
    NULL,
    kDTushort,
    "L=1 U=31",
    0,
    NULL,
    NULL,
    NULL
};

static DTEnumInfo mConfigObringNew_Node_prioTbl[] =
{
    {"high",ENUM_CONFIGOBRINGNEWNODE_PRIO_HIGH,ENMA_CONFIGOBRINGNEWNODE_PRIO_HIGH},
    {"medium",ENUM_CONFIGOBRINGNEWNODE_PRIO_MEDIUM,ENMA_CONFIGOBRINGNEWNODE_PRIO_MEDIUM},
    {"low",ENUM_CONFIGOBRINGNEWNODE_PRIO_LOW,ENMA_CONFIGOBRINGNEWNODE_PRIO_LOW}
};

static DTTypeInfo mConfigObringNew_Node_prioInfo =
{
    "Node type, Enum <high, medium, low>",
    NULL,
    kDTenum,
    "N=3 D=| ",
    0,
    NULL,
    NULL,
    mConfigObringNew_Node_prioTbl
};

static paramDefn mConfigObringNewParams[] =
{
    { "domain_name", kDTstring, mConfigObringNew_Domain_name, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringNew_Domain_nameInfo },
    { "domain_id", kDTushort, mConfigObringNew_Domain_id, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringNew_Domain_idInfo },
    { "node_prio", kDTenum, mConfigObringNew_Node_prio, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigObringNew_Node_prioInfo }
};

static paramEntry mConfigObringNewParamArray[] =
{
    {mConfigObringNew_Domain_name, kRCC_PARAMETER_REQUIRED },
    {mConfigObringNew_Domain_id, kRCC_PARAMETER_REQUIRED },
    {mConfigObringNew_Node_prio, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigObringNewHandlers[] =
{
    { 0, rcc_config_obring_new, 3, mConfigObringNewParamArray }
};

#define kConfigObringNewHelp "\
Create OB-Ring domain\
"

static cmdNode mConfigObringChildren[] =
{ 
    { "delete", kConfigObringDeleteHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mConfigObringDeleteParams, 1, mConfigObringDeleteHandlers },
    { "domain_id", kConfigObringDomain_idHelp, NULL, kRCC_COMMAND_MODE|kRCC_COMMAND_NO_CHAIN|kRCC_COMMAND_CUSTOM1, "config-domain-[[gDomainID]]", 0, 5, mConfigObringDomain_idChildren, 1, mConfigObringDomain_idParams, 1, mConfigObringDomain_idHandlers },
    { "mode", kConfigObringModeHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mConfigObringModeParams, 1, mConfigObringModeHandlers },
    { "new", kConfigObringNewHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 3, mConfigObringNewParams, 1, mConfigObringNewHandlers }
};

#define kConfigObringHelp "\
OB-Ring Protocol\
"

static DTTypeInfo mConfigPort_PortNoInfo =
{
    "Logic port number",
    NULL,
    kDTuinteger,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigPortParams[] =
{
    { "PortNo", kDTuinteger, mConfigPort_PortNo, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigPort_PortNoInfo }
};

static paramEntry mConfigPortParamArray[] =
{
    {mConfigPort_PortNo, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigPortHandlers[] =
{
    { 0, rcc_config_port, 1, mConfigPortParamArray }
};

#define kConfigPortIsolateHelp "\
Port isolate protection\
"

#define kConfigPortNeigbor_probeHelp "\
Enable/disable neigbor probe\
"

static handlerDefn mConfigPortPort_securityHandlers[] =
{
    { kNoHandler, config_port_no_security, 0, NULL },
    { 0, config_port_security, 0, NULL }
};

static DTTypeInfo mConfigPortPort_securityAge_time_Age_timeInfo =
{
    "Age time (1~60 seconds)",
    NULL,
    kDTuinteger,
    "L=1 U=60",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigPortPort_securityAge_timeParams[] =
{
    { "age-time", kDTuinteger, mConfigPortPort_securityAge_time_Age_time, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigPortPort_securityAge_time_Age_timeInfo }
};

static paramEntry mConfigPortPort_securityAge_timeParamArray[] =
{
    {mConfigPortPort_securityAge_time_Age_time, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigPortPort_securityAge_timeHandlers[] =
{
    { 0, rcc_config_port_security_age_time, 1, mConfigPortPort_securityAge_timeParamArray }
};

#define kConfigPortPort_securityAge_timeHelp "\
Age time for dynamic mac address in security port\
"

static DTTypeInfo mConfigPortPort_securityMac_address_Mac_addressInfo =
{
    "Mac address (format: xx:xx:xx:xx:xx:xx)",
    NULL,
    kDTmacaddr,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigPortPort_securityMac_addressParams[] =
{
    { "mac-address", kDTmacaddr, mConfigPortPort_securityMac_address_Mac_address, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigPortPort_securityMac_address_Mac_addressInfo }
};

static paramEntry mConfigPortPort_securityMac_addressParamArray1[] =
{
    {mConfigPortPort_securityMac_address_Mac_address, kRCC_PARAMETER_REQUIRED }
};

static paramEntry mConfigPortPort_securityMac_addressParamArray2[] =
{
    {mConfigPortPort_securityMac_address_Mac_address, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigPortPort_securityMac_addressHandlers[] =
{
    { 0, rcc_config_port_security_macaddr, 1, mConfigPortPort_securityMac_addressParamArray1 },
    { kNoHandler, rcc_config_port_security_no_macaddr, 1, mConfigPortPort_securityMac_addressParamArray2 }
};

#define kConfigPortPort_securityMac_addressHelp "\
Mac address\
"

static DTTypeInfo mConfigPortPort_securityMaximum_MaximumInfo =
{
    "Maximum value (1-132)",
    NULL,
    kDTuinteger,
    "L=1 U=132",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigPortPort_securityMaximumParams[] =
{
    { "maximum", kDTuinteger, mConfigPortPort_securityMaximum_Maximum, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigPortPort_securityMaximum_MaximumInfo }
};

static paramEntry mConfigPortPort_securityMaximumParamArray[] =
{
    {mConfigPortPort_securityMaximum_Maximum, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigPortPort_securityMaximumHandlers[] =
{
    { 0, rcc_config_port_security_maximum, 1, mConfigPortPort_securityMaximumParamArray }
};

#define kConfigPortPort_securityMaximumHelp "\
Maximum address limit per port\
"

static cmdNode mConfigPortPort_securityChildren[] =
{ 
    { "age-time", kConfigPortPort_securityAge_timeHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigPortPort_securityAge_timeParams, 1, mConfigPortPort_securityAge_timeHandlers },
    { "mac-address", kConfigPortPort_securityMac_addressHelp, NULL, kRCC_COMMAND_NO, NULL, 0, 0, NULL, 1, mConfigPortPort_securityMac_addressParams, 2, mConfigPortPort_securityMac_addressHandlers },
    { "maximum", kConfigPortPort_securityMaximumHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigPortPort_securityMaximumParams, 1, mConfigPortPort_securityMaximumHandlers }
};

#define kConfigPortPort_securityHelp "\
Port security configuration for mac limit\
"

#define kConfigPortPvidHelp "\
Set port vlan id\
"

#define kConfigPortSpeed_duplexHelp "\
Set port speed and duplex mode\
"

static cmdNode mConfigPortChildren[] =
{ 
    { "isolate", kConfigPortIsolateHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 0, NULL },
    { "neigbor-probe", kConfigPortNeigbor_probeHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 0, NULL },
    { "port-security", kConfigPortPort_securityHelp, NULL, kRCC_COMMAND_NO, NULL, 0, 3, mConfigPortPort_securityChildren, 0, NULL, 2, mConfigPortPort_securityHandlers },
    { "pvid", kConfigPortPvidHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 0, NULL },
    { "speed-duplex", kConfigPortSpeed_duplexHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 0, NULL }
};

#define kConfigPortHelp "\
Enter specified port configuration mode\
"

#define kConfigRate_limitHelp "\
Rate limit configuration\
"

static handlerDefn mConfigSignalHandlers[] =
{
    { 0, rcc_no_support_display, 0, NULL }
};

static DTTypeInfo mConfigSignalChannum_ChannumInfo =
{
    "Channel number parameter (1-16)",
    NULL,
    kDTuchar,
    "L=1 U=16",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigSignalChannumParams[] =
{
    { "channum", kDTuchar, mConfigSignalChannum_Channum, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalChannum_ChannumInfo }
};

static paramEntry mConfigSignalChannumParamArray[] =
{
    {mConfigSignalChannum_Channum, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigSignalChannumHandlers[] =
{
    { 0, rcc_chan_num_config, 1, mConfigSignalChannumParamArray }
};

#define kConfigSignalChannumHelp "\
Config channel number\
"

static DTTypeInfo mConfigSignalChanparam_ChanidInfo =
{
    "Channel number parameter(1-16)",
    NULL,
    kDTuchar,
    "L=1 U=16",
    0,
    NULL,
    NULL,
    NULL
};

static DTEnumInfo mConfigSignalChanparam_EnableQfsdisableTbl[] =
{
    {"enable",ENUM_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_ENABLE,ENMA_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_ENABLE},
    {"disable",ENUM_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_DISABLE,ENMA_CONFIGSIGNALCHANPARAMENABLEQFSDISABLE_DISABLE}
};

static DTTypeInfo mConfigSignalChanparam_EnableQfsdisableInfo =
{
    "Channel alarm enable/disable",
    NULL,
    kDTenum,
    "N=2 D=| ",
    0,
    NULL,
    NULL,
    mConfigSignalChanparam_EnableQfsdisableTbl
};

static DTEnumInfo mConfigSignalChanparam_AlarmtypeTbl[] =
{
    {"CLOSE",ENUM_CONFIGSIGNALCHANPARAMALARMTYPE_CLOSE,ENMA_CONFIGSIGNALCHANPARAMALARMTYPE_CLOSE},
    {"OPEN",ENUM_CONFIGSIGNALCHANPARAMALARMTYPE_OPEN,ENMA_CONFIGSIGNALCHANPARAMALARMTYPE_OPEN},
    {"DOWN",ENUM_CONFIGSIGNALCHANPARAMALARMTYPE_DOWN,ENMA_CONFIGSIGNALCHANPARAMALARMTYPE_DOWN}
};

static DTTypeInfo mConfigSignalChanparam_AlarmtypeInfo =
{
    "Config channel alarm type, support following type:(CLOSE, OPEN, DOWN)",
    NULL,
    kDTenum,
    "N=3 D=| ",
    0,
    NULL,
    NULL,
    mConfigSignalChanparam_AlarmtypeTbl
};

static paramDefn mConfigSignalChanparamParams[] =
{
    { "chanid", kDTuchar, mConfigSignalChanparam_Chanid, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalChanparam_ChanidInfo },
    { "enable/disable", kDTenum, mConfigSignalChanparam_EnableQfsdisable, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalChanparam_EnableQfsdisableInfo },
    { "alarmtype", kDTenum, mConfigSignalChanparam_Alarmtype, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalChanparam_AlarmtypeInfo }
};

static paramEntry mConfigSignalChanparamParamArray[] =
{
    {mConfigSignalChanparam_Chanid, kRCC_PARAMETER_REQUIRED },
    {mConfigSignalChanparam_EnableQfsdisable, kRCC_PARAMETER_REQUIRED },
    {mConfigSignalChanparam_Alarmtype, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigSignalChanparamHandlers[] =
{
    { 0, rcc_chan_param_config, 3, mConfigSignalChanparamParamArray }
};

#define kConfigSignalChanparamHelp "\
Config channel parameter\
"

static handlerDefn mConfigSignalEnableHandlers[] =
{
    { 0, rcc_signal_enable_config, 0, NULL },
    { kNoHandler, rcc_signal_no_enable_config, 0, NULL }
};

#define kConfigSignalEnableHelp "\
Enable(no enable) signal alarm feature \
"

static DTEnumInfo mConfigSignalJitter_EnableQfsdisableTbl[] =
{
    {"enable",ENUM_CONFIGSIGNALJITTERENABLEQFSDISABLE_ENABLE,ENMA_CONFIGSIGNALJITTERENABLEQFSDISABLE_ENABLE},
    {"disable",ENUM_CONFIGSIGNALJITTERENABLEQFSDISABLE_DISABLE,ENMA_CONFIGSIGNALJITTERENABLEQFSDISABLE_DISABLE}
};

static DTTypeInfo mConfigSignalJitter_EnableQfsdisableInfo =
{
    "Remove jitter enable/disable ",
    NULL,
    kDTenum,
    "N=2 D=| ",
    0,
    NULL,
    NULL,
    mConfigSignalJitter_EnableQfsdisableTbl
};

static DTTypeInfo mConfigSignalJitter_TimeInfo =
{
    "Set jitter probe time (1-200ms)",
    NULL,
    kDTuchar,
    "L=1 U=200",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigSignalJitterParams[] =
{
    { "enable/disable", kDTenum, mConfigSignalJitter_EnableQfsdisable, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalJitter_EnableQfsdisableInfo },
    { "time", kDTuchar, mConfigSignalJitter_Time, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalJitter_TimeInfo }
};

static paramEntry mConfigSignalJitterParamArray[] =
{
    {mConfigSignalJitter_EnableQfsdisable, kRCC_PARAMETER_REQUIRED },
    {mConfigSignalJitter_Time, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigSignalJitterHandlers[] =
{
    { 0, rcc_jitter_config, 2, mConfigSignalJitterParamArray }
};

#define kConfigSignalJitterHelp "\
Config signal jitter feature\
"

static DTTypeInfo mConfigSignalSampcycle_TimeInfo =
{
    "Sample cycle time parameter (1-100ms)",
    NULL,
    kDTuchar,
    "L=1 U=100",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigSignalSampcycleParams[] =
{
    { "time", kDTuchar, mConfigSignalSampcycle_Time, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalSampcycle_TimeInfo }
};

static paramEntry mConfigSignalSampcycleParamArray[] =
{
    {mConfigSignalSampcycle_Time, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigSignalSampcycleHandlers[] =
{
    { 0, rcc_samp_cycle_config, 1, mConfigSignalSampcycleParamArray }
};

#define kConfigSignalSampcycleHelp "\
Config sample cycle time\
"

static handlerDefn mConfigSignalShowHandlers[] =
{
    { 0, rcc_config_signal_show, 0, NULL }
};

#define kConfigSignalShowHelp "\
Display signal alarm startup configuration\
"

static DTEnumInfo mConfigSignalWorkmode_ModeTbl[] =
{
    {"udp",ENUM_CONFIGSIGNALWORKMODEMODE_UDP,ENMA_CONFIGSIGNALWORKMODEMODE_UDP},
    {"tcp",ENUM_CONFIGSIGNALWORKMODEMODE_TCP,ENMA_CONFIGSIGNALWORKMODEMODE_TCP}
};

static DTTypeInfo mConfigSignalWorkmode_ModeInfo =
{
    "Set work mode parameter (udp/tcp)",
    NULL,
    kDTenum,
    "N=2 D=| ",
    0,
    NULL,
    NULL,
    mConfigSignalWorkmode_ModeTbl
};

static DTTypeInfo mConfigSignalWorkmode_IpInfo =
{
    "Set server ip addess",
    NULL,
    kDTipaddress,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mConfigSignalWorkmode_PortInfo =
{
    "Set server port number",
    NULL,
    kDTushort,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigSignalWorkmodeParams[] =
{
    { "mode", kDTenum, mConfigSignalWorkmode_Mode, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalWorkmode_ModeInfo },
    { "ip", kDTipaddress, mConfigSignalWorkmode_Ip, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalWorkmode_IpInfo },
    { "port", kDTushort, mConfigSignalWorkmode_Port, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigSignalWorkmode_PortInfo }
};

static paramEntry mConfigSignalWorkmodeParamArray[] =
{
    {mConfigSignalWorkmode_Mode, kRCC_PARAMETER_REQUIRED },
    {mConfigSignalWorkmode_Ip, kRCC_PARAMETER_REQUIRED },
    {mConfigSignalWorkmode_Port, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigSignalWorkmodeHandlers[] =
{
    { 0, rcc_work_mode_cofig, 3, mConfigSignalWorkmodeParamArray }
};

#define kConfigSignalWorkmodeHelp "\
Config signal alarm work mode\
"

static cmdNode mConfigSignalChildren[] =
{ 
    { "channum", kConfigSignalChannumHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigSignalChannumParams, 1, mConfigSignalChannumHandlers },
    { "chanparam", kConfigSignalChanparamHelp, NULL, 0, NULL, 0, 0, NULL, 3, mConfigSignalChanparamParams, 1, mConfigSignalChanparamHandlers },
    { "enable", kConfigSignalEnableHelp, NULL, kRCC_COMMAND_NO, NULL, 0, 0, NULL, 0, NULL, 2, mConfigSignalEnableHandlers },
    { "jitter", kConfigSignalJitterHelp, NULL, 0, NULL, 0, 0, NULL, 2, mConfigSignalJitterParams, 1, mConfigSignalJitterHandlers },
    { "sampcycle", kConfigSignalSampcycleHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigSignalSampcycleParams, 1, mConfigSignalSampcycleHandlers },
    { "show", kConfigSignalShowHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mConfigSignalShowHandlers },
    { "workmode", kConfigSignalWorkmodeHelp, NULL, 0, NULL, 0, 0, NULL, 3, mConfigSignalWorkmodeParams, 1, mConfigSignalWorkmodeHandlers }
};

#define kConfigSignalHelp "\
Signal alarm configuration\
"

static DTTypeInfo mConfigTraffic_statistic_Port_listInfo =
{
    "Port list, separate by ','. Example: 1,2,4,7",
    NULL,
    kDTstring,
    "T=AL N=32",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigTraffic_statisticParams[] =
{
    { "port-list", kDTstring, mConfigTraffic_statistic_Port_list, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigTraffic_statistic_Port_listInfo }
};

static paramEntry mConfigTraffic_statisticParamArray[] =
{
    {mConfigTraffic_statistic_Port_list, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigTraffic_statisticHandlers[] =
{
    { 0, rcc_config_traffic_statistic, 1, mConfigTraffic_statisticParamArray }
};

#define kConfigTraffic_statisticHelp "\
Traffic statistic configuration\
"

static DTEnumInfo mConfigTrapAdd_TrapTypeTbl[] =
{
    {"REBOOT",ENUM_CONFIGTRAPADDTRAPTYPE_REBOOT,ENMA_CONFIGTRAPADDTRAPTYPE_REBOOT},
    {"PORT",ENUM_CONFIGTRAPADDTRAPTYPE_PORT,ENMA_CONFIGTRAPADDTRAPTYPE_PORT},
    {"RING",ENUM_CONFIGTRAPADDTRAPTYPE_RING,ENMA_CONFIGTRAPADDTRAPTYPE_RING},
    {"VOL",ENUM_CONFIGTRAPADDTRAPTYPE_VOL,ENMA_CONFIGTRAPADDTRAPTYPE_VOL},
    {"TRAFFIC",ENUM_CONFIGTRAPADDTRAPTYPE_TRAFFIC,ENMA_CONFIGTRAPADDTRAPTYPE_TRAFFIC}
};

static DTTypeInfo mConfigTrapAdd_TrapTypeInfo =
{
    "Trap type (REBOOT, PORT, RING, VOL, TRAFFIC)",
    NULL,
    kDTenum,
    "N=5 D=| ",
    0,
    NULL,
    NULL,
    mConfigTrapAdd_TrapTypeTbl
};

static paramDefn mConfigTrapAddParams[] =
{
    { "trapType", kDTenum, mConfigTrapAdd_TrapType, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigTrapAdd_TrapTypeInfo }
};

static paramEntry mConfigTrapAddParamArray[] =
{
    {mConfigTrapAdd_TrapType, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigTrapAddHandlers[] =
{
    { 0, rcc_config_trap_add, 1, mConfigTrapAddParamArray }
};

#define kConfigTrapAddHelp "\
Add a trap type\
"

static DTEnumInfo mConfigTrapDelete_TrapTypeTbl[] =
{
    {"REBOOT",ENUM_CONFIGTRAPDELETETRAPTYPE_REBOOT,ENMA_CONFIGTRAPDELETETRAPTYPE_REBOOT},
    {"PORT",ENUM_CONFIGTRAPDELETETRAPTYPE_PORT,ENMA_CONFIGTRAPDELETETRAPTYPE_PORT},
    {"RING",ENUM_CONFIGTRAPDELETETRAPTYPE_RING,ENMA_CONFIGTRAPDELETETRAPTYPE_RING},
    {"VOL",ENUM_CONFIGTRAPDELETETRAPTYPE_VOL,ENMA_CONFIGTRAPDELETETRAPTYPE_VOL},
    {"TRAFFIC",ENUM_CONFIGTRAPDELETETRAPTYPE_TRAFFIC,ENMA_CONFIGTRAPDELETETRAPTYPE_TRAFFIC}
};

static DTTypeInfo mConfigTrapDelete_TrapTypeInfo =
{
    "Trap type (REBOOT, PORT, RING, VOL, TRAFFIC)",
    NULL,
    kDTenum,
    "N=5 D=| ",
    0,
    NULL,
    NULL,
    mConfigTrapDelete_TrapTypeTbl
};

static paramDefn mConfigTrapDeleteParams[] =
{
    { "trapType", kDTenum, mConfigTrapDelete_TrapType, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigTrapDelete_TrapTypeInfo }
};

static paramEntry mConfigTrapDeleteParamArray[] =
{
    {mConfigTrapDelete_TrapType, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigTrapDeleteHandlers[] =
{
    { 0, rcc_config_trap_delete, 1, mConfigTrapDeleteParamArray }
};

#define kConfigTrapDeleteHelp "\
Delete a trap type\
"

static handlerDefn mConfigTrapEnableHandlers[] =
{
    { 0, rcc_config_trap_enable, 0, NULL },
    { kNoHandler, rcc_config_trap_no_enable, 0, NULL }
};

#define kConfigTrapEnableHelp "\
Enable(no enable) local trap feature \
"

static DTTypeInfo mConfigTrapServer_mac_Mac_addrInfo =
{
    "Mac address",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigTrapServer_macParams[] =
{
    { "mac-addr", kDTstring, mConfigTrapServer_mac_Mac_addr, 0|kRCC_PARAMETER_NOKEYWORD, &mConfigTrapServer_mac_Mac_addrInfo }
};

static paramEntry mConfigTrapServer_macParamArray[] =
{
    {mConfigTrapServer_mac_Mac_addr, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigTrapServer_macHandlers[] =
{
    { 0, rcc_config_trap_server_mac, 1, mConfigTrapServer_macParamArray }
};

#define kConfigTrapServer_macHelp "\
Config trap server mac address\
"

static handlerDefn mConfigTrapShowHandlers[] =
{
    { 0, rcc_config_trap_show, 0, NULL }
};

#define kConfigTrapShowHelp "\
Display local trap configuration\
"

static cmdNode mConfigTrapChildren[] =
{ 
    { "add", kConfigTrapAddHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigTrapAddParams, 1, mConfigTrapAddHandlers },
    { "delete", kConfigTrapDeleteHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigTrapDeleteParams, 1, mConfigTrapDeleteHandlers },
    { "enable", kConfigTrapEnableHelp, NULL, kRCC_COMMAND_NO, NULL, 0, 0, NULL, 0, NULL, 2, mConfigTrapEnableHandlers },
    { "server-mac", kConfigTrapServer_macHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigTrapServer_macParams, 1, mConfigTrapServer_macHandlers },
    { "show", kConfigTrapShowHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mConfigTrapShowHandlers }
};

#define kConfigTrapHelp "\
Local trap configuration\
"

static DTTypeInfo mConfigUserAccess_NameInfo =
{
    "Login",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mConfigUserAccess_AccessInfo =
{
    "Access level",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigUserAccessParams[] =
{
    { "name", kDTstring, mConfigUserAccess_Name, 0, &mConfigUserAccess_NameInfo },
    { "access", kDTstring, mConfigUserAccess_Access, 0, &mConfigUserAccess_AccessInfo }
};

static paramEntry mConfigUserAccessParamArray[] =
{
    {mConfigUserAccess_Name, kRCC_PARAMETER_REQUIRED },
    {mConfigUserAccess_Access, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigUserAccessHandlers[] =
{
    { 0, RCC_EXEC_UserAccess, 2, mConfigUserAccessParamArray }
};

#define kConfigUserAccessHelp "\
Change user access level\
"

static DTTypeInfo mConfigUserAdd_NameInfo =
{
    "User name",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mConfigUserAdd_AccessInfo =
{
    "Access level",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigUserAddParams[] =
{
    { "name", kDTstring, mConfigUserAdd_Name, 0, &mConfigUserAdd_NameInfo },
    { "access", kDTstring, mConfigUserAdd_Access, 0, &mConfigUserAdd_AccessInfo }
};

static paramEntry mConfigUserAddParamArray[] =
{
    {mConfigUserAdd_Name, kRCC_PARAMETER_REQUIRED },
    {mConfigUserAdd_Access, kRCC_PARAMETER_OPTIONAL }
};

static handlerDefn mConfigUserAddHandlers[] =
{
    { 0, RCC_EXEC_UserAdd, 2, mConfigUserAddParamArray }
};

#define kConfigUserAddHelp "\
Add a user\
"

static DTTypeInfo mConfigUserDelete_NameInfo =
{
    "User to delete",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mConfigUserDeleteParams[] =
{
    { "name", kDTstring, mConfigUserDelete_Name, 0, &mConfigUserDelete_NameInfo }
};

static paramEntry mConfigUserDeleteParamArray[] =
{
    {mConfigUserDelete_Name, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigUserDeleteHandlers[] =
{
    { 0, RCC_EXEC_UserDelete, 1, mConfigUserDeleteParamArray }
};

#define kConfigUserDeleteHelp "\
Delete a user\
"

static paramDefn mConfigUserPasswordParams[] =
{
    { NULL, kDTstring, mConfigUserPassword_NULL1, 0, NULL }
};

static paramEntry mConfigUserPasswordParamArray[] =
{
    {mConfigUserPassword_NULL1, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mConfigUserPasswordHandlers[] =
{
    { 0, RCC_EXEC_UserPassword, 1, mConfigUserPasswordParamArray }
};

#define kConfigUserPasswordHelp "\
Change user password\
"

static handlerDefn mConfigUserShowHandlers[] =
{
    { 0, RCC_EXEC_UserShow, 0, NULL }
};

#define kConfigUserShowHelp "\
Show all users\
"

static cmdNode mConfigUserChildren[] =
{ 
    { "access", kConfigUserAccessHelp, NULL, 0, NULL, 0, 0, NULL, 2, mConfigUserAccessParams, 1, mConfigUserAccessHandlers },
    { "add", kConfigUserAddHelp, NULL, 0, NULL, 0, 0, NULL, 2, mConfigUserAddParams, 1, mConfigUserAddHandlers },
    { "delete", kConfigUserDeleteHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigUserDeleteParams, 1, mConfigUserDeleteHandlers },
    { "password", kConfigUserPasswordHelp, NULL, 0, NULL, 0, 0, NULL, 1, mConfigUserPasswordParams, 1, mConfigUserPasswordHandlers },
    { "show", kConfigUserShowHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mConfigUserShowHandlers }
};

#define kConfigUserHelp "\
User configuration\
"

static cmdNode mConfigChildren[] =
{ 
    { "alarm", kConfigAlarmHelp, NULL, kRCC_COMMAND_MODE, "config-alarm", 0, 0, NULL, 0, NULL, 0, NULL },
    { "bootdelay", kConfigBootdelayHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mConfigBootdelayParams, 1, mConfigBootdelayHandlers },
    { "ip", kConfigIpHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 3, mConfigIpParams, 1, mConfigIpHandlers },
    { "mirror", kConfigMirrorHelp, NULL, 0, NULL, 0, 2, mConfigMirrorChildren, 0, NULL, 0, NULL },
    { "obring", kConfigObringHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 4, mConfigObringChildren, 0, NULL, 0, NULL },
    { "port", kConfigPortHelp, NULL, kRCC_COMMAND_MODE, "config-port-[[gPortNo]]", 0, 5, mConfigPortChildren, 1, mConfigPortParams, 1, mConfigPortHandlers },
    { "rate-limit", kConfigRate_limitHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 0, NULL },
    { "signal", kConfigSignalHelp, NULL, kRCC_COMMAND_MODE, "config-signal", 0, 7, mConfigSignalChildren, 0, NULL, 1, mConfigSignalHandlers },
    { "traffic-statistic", kConfigTraffic_statisticHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mConfigTraffic_statisticParams, 1, mConfigTraffic_statisticHandlers },
    { "trap", kConfigTrapHelp, NULL, 0, NULL, 0, 5, mConfigTrapChildren, 0, NULL, 0, NULL },
    { "user", kConfigUserHelp, NULL, 0, NULL, 0, 5, mConfigUserChildren, 0, NULL, 0, NULL }
};

#define kConfigHelp "\
Enter configuration command level\
"

static DTEnumInfo mDebugDiag_Board_nameTbl[] =
{
    {"GE22103MA",ENUM_DEBUGDIAGBOARD_NAME_GE22103MA,ENMA_DEBUGDIAGBOARD_NAME_GE22103MA},
    {"GE2C400U",ENUM_DEBUGDIAGBOARD_NAME_GE2C400U,ENMA_DEBUGDIAGBOARD_NAME_GE2C400U},
    {"GE1040PU",ENUM_DEBUGDIAGBOARD_NAME_GE1040PU,ENMA_DEBUGDIAGBOARD_NAME_GE1040PU}
};

static DTTypeInfo mDebugDiag_Board_nameInfo =
{
    "Diagnostic test for board, support following board:\r\n( GE22103MA, GE2C400U, GE1040PU )",
    NULL,
    kDTenum,
    "N=3 D=| ",
    0,
    NULL,
    NULL,
    mDebugDiag_Board_nameTbl
};

static paramDefn mDebugDiagParams[] =
{
    { "board_name", kDTenum, mDebugDiag_Board_name, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugDiag_Board_nameInfo }
};

static paramEntry mDebugDiagParamArray[] =
{
    {mDebugDiag_Board_name, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugDiagHandlers[] =
{
    { 0, rcc_debug_diag, 1, mDebugDiagParamArray }
};

#define kDebugDiagHelp "\
Diagnostics for board hardware\
"

static DTTypeInfo mDebugEepromClear_OffsetInfo =
{
    "Hexadecimal offset-address of eeprom",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mDebugEepromClear_NbytesInfo =
{
    "Decimal clear size",
    NULL,
    kDTushort,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mDebugEepromClearParams[] =
{
    { "offset", kDTstring, mDebugEepromClear_Offset, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugEepromClear_OffsetInfo },
    { "nbytes", kDTushort, mDebugEepromClear_Nbytes, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugEepromClear_NbytesInfo }
};

static paramEntry mDebugEepromClearParamArray[] =
{
    {mDebugEepromClear_Offset, kRCC_PARAMETER_REQUIRED },
    {mDebugEepromClear_Nbytes, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugEepromClearHandlers[] =
{
    { 0, rcc_debug_eeprom_clear, 2, mDebugEepromClearParamArray }
};

#define kDebugEepromClearHelp "\
Clear eeprom data\
"

static DTTypeInfo mDebugEepromDump_OffsetInfo =
{
    "Hexadecimal offset-address of eeprom",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mDebugEepromDump_NbytesInfo =
{
    "Decimal dump size",
    NULL,
    kDTushort,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mDebugEepromDumpParams[] =
{
    { "offset", kDTstring, mDebugEepromDump_Offset, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugEepromDump_OffsetInfo },
    { "nbytes", kDTushort, mDebugEepromDump_Nbytes, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugEepromDump_NbytesInfo }
};

static paramEntry mDebugEepromDumpParamArray[] =
{
    {mDebugEepromDump_Offset, kRCC_PARAMETER_REQUIRED },
    {mDebugEepromDump_Nbytes, kRCC_PARAMETER_OPTIONAL }
};

static handlerDefn mDebugEepromDumpHandlers[] =
{
    { 0, rcc_debug_eeprom_dump, 2, mDebugEepromDumpParamArray }
};

#define kDebugEepromDumpHelp "\
Dump eeprom data\
"

static handlerDefn mDebugEepromFormatHandlers[] =
{
    { 0, rcc_debug_eeprom_format, 0, NULL }
};

#define kDebugEepromFormatHelp "\
Format eeprom\
"

static DTTypeInfo mDebugEepromTest_OffsetInfo =
{
    "Hexadecimal offset-address of eeprom",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mDebugEepromTest_NbytesInfo =
{
    "Decimal size to write",
    NULL,
    kDTushort,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mDebugEepromTest_ValueInfo =
{
    "The value to write",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mDebugEepromTestParams[] =
{
    { "offset", kDTstring, mDebugEepromTest_Offset, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugEepromTest_OffsetInfo },
    { "nbytes", kDTushort, mDebugEepromTest_Nbytes, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugEepromTest_NbytesInfo },
    { "value", kDTstring, mDebugEepromTest_Value, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugEepromTest_ValueInfo }
};

static paramEntry mDebugEepromTestParamArray[] =
{
    {mDebugEepromTest_Offset, kRCC_PARAMETER_REQUIRED },
    {mDebugEepromTest_Nbytes, kRCC_PARAMETER_REQUIRED },
    {mDebugEepromTest_Value, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugEepromTestHandlers[] =
{
    { 0, rcc_debug_eeprom_test, 3, mDebugEepromTestParamArray }
};

#define kDebugEepromTestHelp "\
Test eeprom write\
"

static cmdNode mDebugEepromChildren[] =
{ 
    { "clear", kDebugEepromClearHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 2, mDebugEepromClearParams, 1, mDebugEepromClearHandlers },
    { "dump", kDebugEepromDumpHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 2, mDebugEepromDumpParams, 1, mDebugEepromDumpHandlers },
    { "format", kDebugEepromFormatHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mDebugEepromFormatHandlers },
    { "test", kDebugEepromTestHelp, NULL, 0, NULL, 0, 0, NULL, 3, mDebugEepromTestParams, 1, mDebugEepromTestHandlers }
};

#define kDebugEepromHelp "\
Eeprom data operation\
"

static DTEnumInfo mDebugLogin_EnableQppdisableTbl[] =
{
    {"enable",ENUM_DEBUGLOGINENABLEQPPDISABLE_ENABLE,ENMA_DEBUGLOGINENABLEQPPDISABLE_ENABLE},
    {"disable",ENUM_DEBUGLOGINENABLEQPPDISABLE_DISABLE,ENMA_DEBUGLOGINENABLEQPPDISABLE_DISABLE}
};

static DTTypeInfo mDebugLogin_EnableQppdisableInfo =
{
    "Enable: you must input password before enter CLI\r\nDisable: skip login and enter CLI directly ",
    NULL,
    kDTenum,
    "N=2 D=| ",
    0,
    NULL,
    NULL,
    mDebugLogin_EnableQppdisableTbl
};

static paramDefn mDebugLoginParams[] =
{
    { "enable|disable", kDTenum, mDebugLogin_EnableQppdisable, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugLogin_EnableQppdisableInfo }
};

static paramEntry mDebugLoginParamArray[] =
{
    {mDebugLogin_EnableQppdisable, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugLoginHandlers[] =
{
    { 0, rcc_debug_login, 1, mDebugLoginParamArray }
};

#define kDebugLoginHelp "\
CLI Login enable/disable\
"

static DTEnumInfo mDebugModule_AddQppdelQppshowTbl[] =
{
    {"add",ENUM_DEBUGMODULEADDQPPDELQPPSHOW_ADD,ENMA_DEBUGMODULEADDQPPDELQPPSHOW_ADD},
    {"del",ENUM_DEBUGMODULEADDQPPDELQPPSHOW_DEL,ENMA_DEBUGMODULEADDQPPDELQPPSHOW_DEL},
    {"show",ENUM_DEBUGMODULEADDQPPDELQPPSHOW_SHOW,ENMA_DEBUGMODULEADDQPPDELQPPSHOW_SHOW}
};

static DTTypeInfo mDebugModule_AddQppdelQppshowInfo =
{
    "Debug module add/del/show\r\nadd: enable module debug\r\ndel: disable module debug\r\nshow: display debug-module",
    NULL,
    kDTenum,
    "N=3 D=| ",
    0,
    NULL,
    NULL,
    mDebugModule_AddQppdelQppshowTbl
};

static DTEnumInfo mDebugModule_ModuleTbl[] =
{
    {"nms",ENUM_DEBUGMODULEMODULE_NMS,ENMA_DEBUGMODULEMODULE_NMS},
    {"obring",ENUM_DEBUGMODULEMODULE_OBRING,ENMA_DEBUGMODULEMODULE_OBRING},
    {"uart",ENUM_DEBUGMODULEMODULE_UART,ENMA_DEBUGMODULEMODULE_UART}
};

static DTTypeInfo mDebugModule_ModuleInfo =
{
    "Module name, support following module name:\r\n<nms,obring,uart>",
    NULL,
    kDTenum,
    "N=3 D=| ",
    0,
    NULL,
    NULL,
    mDebugModule_ModuleTbl
};

static paramDefn mDebugModuleParams[] =
{
    { "add|del|show", kDTenum, mDebugModule_AddQppdelQppshow, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugModule_AddQppdelQppshowInfo },
    { "module", kDTenum, mDebugModule_Module, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugModule_ModuleInfo }
};

static paramEntry mDebugModuleParamArray[] =
{
    {mDebugModule_AddQppdelQppshow, kRCC_PARAMETER_REQUIRED },
    {mDebugModule_Module, kRCC_PARAMETER_OPTIONAL }
};

static handlerDefn mDebugModuleHandlers[] =
{
    { 0, rcc_debug_module, 2, mDebugModuleParamArray }
};

#define kDebugModuleHelp "\
Module debug control\
"

static DTTypeInfo mDebugObringDisable_Ring_indexInfo =
{
    "Ring index (0-15)",
    NULL,
    kDTuchar,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mDebugObringDisableParams[] =
{
    { "ring_index", kDTuchar, mDebugObringDisable_Ring_index, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugObringDisable_Ring_indexInfo }
};

static paramEntry mDebugObringDisableParamArray[] =
{
    {mDebugObringDisable_Ring_index, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugObringDisableHandlers[] =
{
    { 0, rcc_debug_obring_disable, 1, mDebugObringDisableParamArray }
};

#define kDebugObringDisableHelp "\
Disable all nodes OB-Ring protocol\
"

static DTTypeInfo mDebugObringEnable_Ring_indexInfo =
{
    "Ring index (0-15)",
    NULL,
    kDTuchar,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mDebugObringEnableParams[] =
{
    { "ring_index", kDTuchar, mDebugObringEnable_Ring_index, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugObringEnable_Ring_indexInfo }
};

static paramEntry mDebugObringEnableParamArray[] =
{
    {mDebugObringEnable_Ring_index, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugObringEnableHandlers[] =
{
    { 0, rcc_debug_obring_enable, 1, mDebugObringEnableParamArray }
};

#define kDebugObringEnableHelp "\
Enable all nodes OB-Ring protocol\
"

static DTTypeInfo mDebugObringReboot_Ring_indexInfo =
{
    "Ring index (0-15)",
    NULL,
    kDTuchar,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mDebugObringRebootParams[] =
{
    { "ring_index", kDTuchar, mDebugObringReboot_Ring_index, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugObringReboot_Ring_indexInfo }
};

static paramEntry mDebugObringRebootParamArray[] =
{
    {mDebugObringReboot_Ring_index, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugObringRebootHandlers[] =
{
    { 0, rcc_debug_obring_reboot, 1, mDebugObringRebootParamArray }
};

#define kDebugObringRebootHelp "\
Reboot all nodes \
"

static cmdNode mDebugObringChildren[] =
{ 
    { "disable", kDebugObringDisableHelp, NULL, 0, NULL, 0, 0, NULL, 1, mDebugObringDisableParams, 1, mDebugObringDisableHandlers },
    { "enable", kDebugObringEnableHelp, NULL, 0, NULL, 0, 0, NULL, 1, mDebugObringEnableParams, 1, mDebugObringEnableHandlers },
    { "reboot", kDebugObringRebootHelp, NULL, 0, NULL, 0, 0, NULL, 1, mDebugObringRebootParams, 1, mDebugObringRebootHandlers }
};

#define kDebugObringHelp "\
Batch all OB-Ring nodes\
"

static DTTypeInfo mDebugSwitchGetreg_PageInfo =
{
    "Select page value",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mDebugSwitchGetreg_AddressInfo =
{
    "Address range, separated by character '-',\r\nand max address is 0xFF, max address len is 8",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mDebugSwitchGetregParams[] =
{
    { "page", kDTstring, mDebugSwitchGetreg_Page, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugSwitchGetreg_PageInfo },
    { "address", kDTstring, mDebugSwitchGetreg_Address, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugSwitchGetreg_AddressInfo }
};

static paramEntry mDebugSwitchGetregParamArray[] =
{
    {mDebugSwitchGetreg_Page, kRCC_PARAMETER_REQUIRED },
    {mDebugSwitchGetreg_Address, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugSwitchGetregHandlers[] =
{
    { 0, rcc_debug_switch_getreg, 2, mDebugSwitchGetregParamArray }
};

#define kDebugSwitchGetregHelp "\
Get the register value\
"

static DTTypeInfo mDebugSwitchSetreg_PageInfo =
{
    "Select page value",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mDebugSwitchSetreg_AddressInfo =
{
    "Address range, separated by character '-',\r\nand max address is 0xFF, max address len is 8",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mDebugSwitchSetreg_ValueInfo =
{
    "Value string, separated by character '-'",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mDebugSwitchSetregParams[] =
{
    { "page", kDTstring, mDebugSwitchSetreg_Page, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugSwitchSetreg_PageInfo },
    { "address", kDTstring, mDebugSwitchSetreg_Address, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugSwitchSetreg_AddressInfo },
    { "value", kDTstring, mDebugSwitchSetreg_Value, 0|kRCC_PARAMETER_NOKEYWORD, &mDebugSwitchSetreg_ValueInfo }
};

static paramEntry mDebugSwitchSetregParamArray[] =
{
    {mDebugSwitchSetreg_Page, kRCC_PARAMETER_REQUIRED },
    {mDebugSwitchSetreg_Address, kRCC_PARAMETER_REQUIRED },
    {mDebugSwitchSetreg_Value, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mDebugSwitchSetregHandlers[] =
{
    { 0, rcc_debug_switch_setreg, 3, mDebugSwitchSetregParamArray }
};

#define kDebugSwitchSetregHelp "\
Set the register value\
"

static cmdNode mDebugSwitchChildren[] =
{ 
    { "getreg", kDebugSwitchGetregHelp, NULL, 0, NULL, 0, 0, NULL, 2, mDebugSwitchGetregParams, 1, mDebugSwitchGetregHandlers },
    { "setreg", kDebugSwitchSetregHelp, NULL, 0, NULL, 0, 0, NULL, 3, mDebugSwitchSetregParams, 1, mDebugSwitchSetregHandlers }
};

#define kDebugSwitchHelp "\
Switch register opertion\
"

static cmdNode mDebugChildren[] =
{ 
    { "diag", kDebugDiagHelp, NULL, 0, NULL, 0, 0, NULL, 1, mDebugDiagParams, 1, mDebugDiagHandlers },
    { "eeprom", kDebugEepromHelp, NULL, 0, NULL, 0, 4, mDebugEepromChildren, 0, NULL, 0, NULL },
    { "login", kDebugLoginHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mDebugLoginParams, 1, mDebugLoginHandlers },
    { "module", kDebugModuleHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 2, mDebugModuleParams, 1, mDebugModuleHandlers },
    { "obring", kDebugObringHelp, NULL, 0, NULL, 0, 3, mDebugObringChildren, 0, NULL, 0, NULL },
    { "switch", kDebugSwitchHelp, NULL, kRCC_COMMAND_MODE, "debug-switch", 0, 2, mDebugSwitchChildren, 0, NULL, 0, NULL }
};

#define kDebugHelp "\
Enter debug command level\
"

static handlerDefn mEnableHandlers[] =
{
    { 0, rcc_exec_enable, 0, NULL }
};

#define kEnableHelp "\
Turn on privileged commands\
"

static DTTypeInfo mExit_AllInfo =
{
    "Exit to root",
    NULL,
    kDTabsolute,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mExitParams[] =
{
    { "all", kDTabsolute, mExit_All, 0, &mExit_AllInfo }
};

static paramEntry mExitParamArray[] =
{
    {mExit_All, kRCC_PARAMETER_OPTIONAL }
};

static handlerDefn mExitHandlers[] =
{
    { 0, rcc_exec_exit, 1, mExitParamArray }
};

#define kExitHelp "\
Exit intermediate mode\
"

static DTTypeInfo mHelp_CommandsInfo =
{
    "System help",
    NULL,
    kDTabsolute,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mHelp_EditInfo =
{
    "Show editing keys",
    NULL,
    kDTabsolute,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mHelpParams[] =
{
    { "commands", kDTabsolute, mHelp_Commands, 0, &mHelp_CommandsInfo },
    { "edit", kDTabsolute, mHelp_Edit, 0, &mHelp_EditInfo }
};

static paramEntry mHelpParamArray2[] =
{
    {mHelp_Edit, kRCC_PARAMETER_REQUIRED }
};

static paramEntry mHelpParamArray3[] =
{
    {mHelp_Commands, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mHelpHandlers[] =
{
    { 0, RCC_EXEC_Help, 0, NULL },
    { 0, RCC_EXEC_HelpEdit, 1, mHelpParamArray2 },
    { 0, RCC_EXEC_HelpGlobals, 1, mHelpParamArray3 }
};

#define kHelpHelp "\
Show command help\
"

static handlerDefn mHistoryHandlers[] =
{
    { 0, rcc_exec_history, 0, NULL }
};

#define kHistoryHelp "\
Show command history\
"

static DTTypeInfo mPing_Host_ipInfo =
{
    "Destinaton ip address",
    NULL,
    kDTipaddress,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mPingParams[] =
{
    { "host ip", kDTipaddress, mPing_Host_ip, 0|kRCC_PARAMETER_NOKEYWORD, &mPing_Host_ipInfo }
};

static paramEntry mPingParamArray[] =
{
    {mPing_Host_ip, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mPingHandlers[] =
{
    { 0, rcc_exec_ping, 1, mPingParamArray }
};

#define kPingHelp "\
Verify network connectivity\
"

static handlerDefn mResetHandlers[] =
{
    { 0, rcc_exec_reset, 0, NULL }
};

#define kResetHelp "\
Restart the system\
"

static handlerDefn mShowAlarmSignalHandlers[] =
{
    { 0, rcc_show_signal, 0, NULL }
};

#define kShowAlarmSignalHelp "\
Diaplay switch signal running configuration\
"

static cmdNode mShowAlarmChildren[] =
{ 
    { "signal", kShowAlarmSignalHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mShowAlarmSignalHandlers }
};

#define kShowAlarmHelp "\
Diaplay switch signal running configuration\
"

static DTTypeInfo mShowCounters_PortInfo =
{
    "Logic port number",
    NULL,
    kDTuchar,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mShowCountersParams[] =
{
    { "port", kDTuchar, mShowCounters_Port, 0|kRCC_PARAMETER_NOKEYWORD, &mShowCounters_PortInfo }
};

static paramEntry mShowCountersParamArray[] =
{
    {mShowCounters_Port, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mShowCountersHandlers[] =
{
    { 0, rcc_show_counters, 1, mShowCountersParamArray }
};

#define kShowCountersHelp "\
Display port statistics information\
"

static handlerDefn mShowDeviceHandlers[] =
{
    { 0, rcc_show_device, 0, NULL }
};

#define kShowDeviceHelp "\
Display device node information\
"

static handlerDefn mShowMac_address_tableHandlers[] =
{
    { 0, rcc_show_mac_addr_table, 0, NULL }
};

#define kShowMac_address_tableHelp "\
Display MAC address table\
"

static handlerDefn mShowMemoryHandlers[] =
{
    { 0, rcc_exec_show_memory, 0, NULL }
};

#define kShowMemoryHelp "\
Display the information of memory\
"

static DTTypeInfo mShowObring_TopoInfo =
{
    "Display the topology of OB-Ring device",
    NULL,
    kDTabsolute,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mShowObringParams[] =
{
    { "topo", kDTabsolute, mShowObring_Topo, 0, &mShowObring_TopoInfo }
};

static paramEntry mShowObringParamArray2[] =
{
    {mShowObring_Topo, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mShowObringHandlers[] =
{
    { 0, rcc_exec_show_obring, 0, NULL },
    { 0, rcc_exec_show_obring_topo, 1, mShowObringParamArray2 }
};

#define kShowObringHelp "\
Display OB-Ring protocol information\
"

static handlerDefn mShowPort_configHandlers[] =
{
    { 0, rcc_exec_show_port_config, 0, NULL }
};

#define kShowPort_configHelp "\
Display all switch ports configuration\
"

static handlerDefn mShowPort_neigborHandlers[] =
{
    { 0, rcc_exec_show_port_neigbor, 0, NULL }
};

#define kShowPort_neigborHelp "\
Display all switch ports neigbor info\
"

static handlerDefn mShowPort_statusHandlers[] =
{
    { 0, rcc_exec_show_port_status, 0, NULL }
};

#define kShowPort_statusHelp "\
Display all switch ports status\
"

static handlerDefn mShowPort_trafficHandlers[] =
{
    { 0, rcc_exec_show_port_traffic, 0, NULL }
};

#define kShowPort_trafficHelp "\
Display all switch ports traffic info\
"

static handlerDefn mShowQosMapHandlers[] =
{
    { 0, rcc_show_priority_queue_map, 0, NULL }
};

#define kShowQosMapHelp "\
Display QoS priority-queue running configuration\
"

static handlerDefn mShowQosSetHandlers[] =
{
    { 0, rcc_show_qos_set, 0, NULL }
};

#define kShowQosSetHelp "\
Display QoS setting running configuration\
"

static cmdNode mShowQosChildren[] =
{ 
    { "map", kShowQosMapHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mShowQosMapHandlers },
    { "set", kShowQosSetHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mShowQosSetHandlers }
};

#define kShowQosHelp "\
Display QoS running configuration\
"

static DTTypeInfo mShowRegister_PageInfo =
{
    "The page(Decimal) of register",
    NULL,
    kDTuchar,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mShowRegister_AddressInfo =
{
    "The address(Decimal) of register",
    NULL,
    kDTuchar,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTTypeInfo mShowRegister_LenthInfo =
{
    "The byte lenth(Decimal) of register",
    NULL,
    kDTuchar,
    "L=1 U=8",
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mShowRegisterParams[] =
{
    { "page", kDTuchar, mShowRegister_Page, 0|kRCC_PARAMETER_NOKEYWORD, &mShowRegister_PageInfo },
    { "address", kDTuchar, mShowRegister_Address, 0|kRCC_PARAMETER_NOKEYWORD, &mShowRegister_AddressInfo },
    { "lenth", kDTuchar, mShowRegister_Lenth, 0|kRCC_PARAMETER_NOKEYWORD, &mShowRegister_LenthInfo }
};

static paramEntry mShowRegisterParamArray[] =
{
    {mShowRegister_Page, kRCC_PARAMETER_REQUIRED },
    {mShowRegister_Address, kRCC_PARAMETER_REQUIRED },
    {mShowRegister_Lenth, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mShowRegisterHandlers[] =
{
    { 0, rcc_exec_show_register, 3, mShowRegisterParamArray }
};

#define kShowRegisterHelp "\
Display switch chip register data\
"

static handlerDefn mShowSystemHandlers[] =
{
    { 0, rcc_show_system, 0, NULL }
};

#define kShowSystemHelp "\
Display the system information\
"

static DTTypeInfo mShowTask_RuntimeInfo =
{
    "Show the task runing time",
    NULL,
    kDTabsolute,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mShowTaskParams[] =
{
    { "runtime", kDTabsolute, mShowTask_Runtime, 0, &mShowTask_RuntimeInfo }
};

static paramEntry mShowTaskParamArray2[] =
{
    {mShowTask_Runtime, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mShowTaskHandlers[] =
{
    { 0, rcc_show_task, 0, NULL },
    { 0, rcc_show_task_runtime, 1, mShowTaskParamArray2 }
};

#define kShowTaskHelp "\
Display the active task information\
"

static DTTypeInfo mShowUart_PortInfo =
{
    "Uart port (port=0,1)",
    NULL,
    kDTuchar,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mShowUartParams[] =
{
    { "port", kDTuchar, mShowUart_Port, 0|kRCC_PARAMETER_NOKEYWORD, &mShowUart_PortInfo }
};

static paramEntry mShowUartParamArray[] =
{
    {mShowUart_Port, kRCC_PARAMETER_OPTIONAL }
};

static handlerDefn mShowUartHandlers[] =
{
    { 0, rcc_show_uart, 1, mShowUartParamArray }
};

#define kShowUartHelp "\
Display the uart server running stats\
"

static handlerDefn mShowVersionHandlers[] =
{
    { 0, rcc_exec_show_version, 0, NULL }
};

#define kShowVersionHelp "\
Display the version information\
"

static handlerDefn mShowVlanHandlers[] =
{
    { 0, rcc_show_vlan, 0, NULL }
};

#define kShowVlanHelp "\
Display VTU table\
"

static cmdNode mShowChildren[] =
{ 
    { "alarm", kShowAlarmHelp, NULL, kRCC_COMMAND_MODE, "show-alarm", 0, 1, mShowAlarmChildren, 0, NULL, 0, NULL },
    { "counters", kShowCountersHelp, NULL, 0, NULL, 0, 0, NULL, 1, mShowCountersParams, 1, mShowCountersHandlers },
    { "device", kShowDeviceHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mShowDeviceHandlers },
    { "mac-address-table", kShowMac_address_tableHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mShowMac_address_tableHandlers },
    { "memory", kShowMemoryHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0 |ENUM_ACCESS_ENABLE, 0, NULL, 0, NULL, 1, mShowMemoryHandlers },
    { "obring", kShowObringHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mShowObringParams, 2, mShowObringHandlers },
    { "port-config", kShowPort_configHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mShowPort_configHandlers },
    { "port-neigbor", kShowPort_neigborHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mShowPort_neigborHandlers },
    { "port-status", kShowPort_statusHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mShowPort_statusHandlers },
    { "port-traffic", kShowPort_trafficHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mShowPort_trafficHandlers },
    { "qos", kShowQosHelp, NULL, 0, NULL, 0, 2, mShowQosChildren, 0, NULL, 0, NULL },
    { "register", kShowRegisterHelp, NULL, 0, NULL, 0, 0, NULL, 3, mShowRegisterParams, 1, mShowRegisterHandlers },
    { "system", kShowSystemHelp, NULL, 0, NULL, 0, 0, NULL, 0, NULL, 1, mShowSystemHandlers },
    { "task", kShowTaskHelp, NULL, 0, NULL, 0, 0, NULL, 1, mShowTaskParams, 2, mShowTaskHandlers },
    { "uart", kShowUartHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mShowUartParams, 1, mShowUartHandlers },
    { "version", kShowVersionHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mShowVersionHandlers },
    { "vlan", kShowVlanHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mShowVlanHandlers }
};

#define kShowHelp "\
Show running system information\
"

static DTTypeInfo mTftp_Server_ipInfo =
{
    "TFTP Server IP address",
    NULL,
    kDTipaddress,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static DTEnumInfo mTftp_GetQppputTbl[] =
{
    {"get",ENUM_TFTPGETQPPPUT_GET,ENMA_TFTPGETQPPPUT_GET},
    {"put",ENUM_TFTPGETQPPPUT_PUT,ENMA_TFTPGETQPPPUT_PUT}
};

static DTTypeInfo mTftp_GetQppputInfo =
{
    "get: get file from remote host\r\nput: put file onto remote host",
    NULL,
    kDTenum,
    "N=2 D=| ",
    0,
    NULL,
    NULL,
    mTftp_GetQppputTbl
};

static DTTypeInfo mTftp_FilenameInfo =
{
    "The remote filename",
    NULL,
    kDTstring,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mTftpParams[] =
{
    { "server-ip", kDTipaddress, mTftp_Server_ip, 0|kRCC_PARAMETER_NOKEYWORD, &mTftp_Server_ipInfo },
    { "get|put", kDTenum, mTftp_GetQppput, 0|kRCC_PARAMETER_NOKEYWORD, &mTftp_GetQppputInfo },
    { "filename", kDTstring, mTftp_Filename, 0|kRCC_PARAMETER_NOKEYWORD, &mTftp_FilenameInfo }
};

static paramEntry mTftpParamArray[] =
{
    {mTftp_Server_ip, kRCC_PARAMETER_REQUIRED },
    {mTftp_GetQppput, kRCC_PARAMETER_REQUIRED },
    {mTftp_Filename, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mTftpHandlers[] =
{
    { 0, rcc_exec_tftp, 3, mTftpParamArray }
};

#define kTftpHelp "\
Upgrade firmware by tftp protocal\
"

static DTTypeInfo mTree__syntaxInfo =
{
    "show full command syntax in tree",
    NULL,
    kDTabsolute,
    NULL,
    0,
    NULL,
    NULL,
    NULL
};

static paramDefn mTreeParams[] =
{
    { "-syntax", kDTabsolute, mTree__syntax, 0, &mTree__syntaxInfo }
};

static paramEntry mTreeParamArray[] =
{
    {mTree__syntax, kRCC_PARAMETER_REQUIRED }
};

static handlerDefn mTreeHandlers[] =
{
    { 0, rcc_exec_tree, 1, mTreeParamArray }
};

#define kTreeHelp "\
Show command tree\
"

static cmdNode mRootChildren[] =
{ 
    { "clear", kClearHelp, NULL, 0, NULL, 0 |ENUM_ACCESS_ENABLE, 2, mClearChildren, 0, NULL, 0, NULL },
    { "config", kConfigHelp, NULL, kRCC_COMMAND_MODE, "config", 0 |ENUM_ACCESS_ENABLE, 11, mConfigChildren, 0, NULL, 0, NULL },
    { "debug", kDebugHelp, NULL, kRCC_COMMAND_MODE, "debug", 0 |ENUM_ACCESS_ENABLE, 6, mDebugChildren, 0, NULL, 0, NULL },
    { "enable", kEnableHelp, NULL, kRCC_COMMAND_NO|kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 0, NULL, 1, mEnableHandlers },
    { "exit", kExitHelp, NULL, kRCC_COMMAND_GLOBAL|kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mExitParams, 1, mExitHandlers },
    { "help", kHelpHelp, NULL, kRCC_COMMAND_GLOBAL|kRCC_COMMAND_META, NULL, 0, 0, NULL, 2, mHelpParams, 3, mHelpHandlers },
    { "history", kHistoryHelp, NULL, kRCC_COMMAND_GLOBAL, NULL, 0, 0, NULL, 0, NULL, 1, mHistoryHandlers },
    { "ping", kPingHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0 |ENUM_ACCESS_ENABLE, 0, NULL, 1, mPingParams, 1, mPingHandlers },
    { "reset", kResetHelp, NULL, kRCC_COMMAND_CUSTOM1, NULL, 0 |ENUM_ACCESS_ENABLE, 0, NULL, 0, NULL, 1, mResetHandlers },
    { "show", kShowHelp, NULL, kRCC_COMMAND_MODE, "show", 0 |ENUM_ACCESS_ENABLE, 17, mShowChildren, 0, NULL, 0, NULL },
    { "tftp", kTftpHelp, NULL, 0, NULL, 0 |ENUM_ACCESS_ENABLE, 0, NULL, 3, mTftpParams, 1, mTftpHandlers },
    { "tree", kTreeHelp, NULL, kRCC_COMMAND_GLOBAL|kRCC_COMMAND_META|kRCC_COMMAND_CUSTOM1, NULL, 0, 0, NULL, 1, mTreeParams, 1, mTreeHandlers }
};

cmdNode	mRootCmdNode = { NULL, NULL, NULL, 0, NULL, 0,  12, mRootChildren, 0, NULL, 0, NULL };

