/*  
 *  rcc_handlers.c
 *
 *  This is a part of the RapidControl SDK source code library. 
 *
 *  Copyright (C) 2001 WindRiver Systems
 *  Version 3.30
 *  All rights reserved.
 *
 */

/* 
 * This file was automatically generated by a RapidControl Integration Tool.
 * The purpose of this file is to provide you with template code in further
 * developing the handler functions for your CLI.  Depending on the 
 * configuration you specified in the RCIT, the handler functions below will 
 * make appropriate API calls to:
 *
 * 1) retrieve optional or required parameter data from the parse engine
 * 2) access RapidMarks for either read or write operations
 * 3) display the data, as appropriate
 *
 * We anticipate that this generated code will serve about 70-90% of your 
 * needs, and that it will save you substantial amounts of time in actually
 * developing your handler functions.  However, we also anticipate that
 * you will have to modify the generated code to fully work with your 
 * system.
 *
 * BEWARE, THOUGH, THAT THIS FILE IS AUTOMATICALLY GENERATED FROM SCRATCH 
 * EACH TIME YOU USE THE RCIT.  IF YOU MODIFY THE HANDLER FUNCTIONS BELOW,  
 * AND REGENERATE THE FILE, YOU WILL LOSE YOUR MODIFICATIONS.
 *
 * Because of this, we recommend that you use the Custom Code feature in the 
 * handler edit dialog box, or cut-and-paste the generated code into another file 
 * (and make your modifications there), or that you rename the file each 
 * code-generation-cycle, or a combination of the above.
 *
 */


#include "rc.h"
#include "rc_ignition.h"
#include "rcc.h"
#include "rcc_cli.h"

/* Handlers Preamble */

#include "mconfig.h"
#include "cli_sys.h"


/* <RccHandlerPartition=DEFAULT> */
/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_clear_counters(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_clear_counters_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_clear_mac_addr_table(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
   status = cli_clear_mac_addr_table_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_bootdelay(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
	
	status = cli_config_bootdelay_handler(pCliEnv, pParams, pAuxBuf);
    
	return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_ip(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_ip_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_mirror_destination_port(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    sbyte       *pVal1 = NULL;
    paramDescr  *pParamDescr1;
    sbyte       *pVal2 = NULL;
    paramDescr  *pParamDescr2;

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "port", mConfigMirrorDestination_port_Port, &pParamDescr1 );
    if ( OK != status )
    {
		return(status);
    } else pVal1 = (sbyte*)(pParamDescr1->pValue);

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "direction", mConfigMirrorDestination_port_Direction, &pParamDescr2 );
    if ( OK != status )
    {
		return(status);
    } else pVal2 = (sbyte*)(pParamDescr2->pValue);

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_mirror_source_port(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    sbyte       *pVal1 = NULL;
    paramDescr  *pParamDescr1;
    sbyte       *pVal2 = NULL;
    paramDescr  *pParamDescr2;

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "portlist", mConfigMirrorSource_port_Portlist, &pParamDescr1 );
    if ( OK != status )
    {
		return(status);
    } else pVal1 = (sbyte*)(pParamDescr1->pValue);

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "direction", mConfigMirrorSource_port_Direction, &pParamDescr2 );
    if ( OK != status )
    {
		return(status);
    } else pVal2 = (sbyte*)(pParamDescr2->pValue);

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_delete(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_delete_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_domain(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_domain_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_enable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_domain_enable_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_no_enable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_domain_disable_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_domain_fail_times(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_domain_fail_times_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_domain_hello_times(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_domain_hello_times_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_domain_primary_port_disable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_domain_primary_port_disable_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_domain_primary_port_enable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_domain_primary_port_enable_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_domain_ring_port(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_domain_ring_port_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_mode(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_mode_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_obring_new(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_obring_new_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_port(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
	
	status = cli_config_port_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
config_port_no_security(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_port_no_security_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
config_port_security(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_config_port_security_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_port_security_age_time(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    sbyte       *pVal = NULL;
    paramDescr  *pParamDescr;

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "age-time", mConfigPortPort_securityAge_time_Age_time, &pParamDescr );
    if ( OK != status )
    {
		return(status);
    } else pVal = (sbyte*)(pParamDescr->pValue);

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_port_security_macaddr(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
	
	status = cli_config_port_security_macaddr_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_port_security_no_macaddr(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    sbyte       *pVal = NULL;
    paramDescr  *pParamDescr;

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "mac-address", mConfigPortPort_securityMac_address_Mac_address, &pParamDescr );
    if ( OK != status )
    {
		return(status);
    } else pVal = (sbyte*)(pParamDescr->pValue);

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_port_security_maximum(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
	
	status = cli_config_port_security_maximum_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_no_support_display(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
#else
    status = cli_no_support_display_handler(pCliEnv, pParams, pAuxBuf);

    return  status;
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_chan_num_config(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
    status = cli_chan_num_config_handler(pCliEnv, pParams, pAuxBuf);
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_chan_param_config(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
    status = cli_chan_param_config_handler(pCliEnv, pParams, pAuxBuf);
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_signal_enable_config(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
    status = cli_signal_enable_config_handler(pCliEnv, pParams, pAuxBuf);
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_signal_no_enable_config(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
    status = cli_signal_no_enable_config_handler(pCliEnv, pParams, pAuxBuf);
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_jitter_config(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
    status = cli_jitter_config_handler(pCliEnv, pParams, pAuxBuf);
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_samp_cycle_config(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
    status = cli_samp_cycle_config_handler(pCliEnv, pParams, pAuxBuf);
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_signal_show(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
    status = cli_show_signal_handler(pCliEnv, pParams, pAuxBuf);
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_work_mode_cofig(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
#if MODULE_SIGNAL
    status = cli_work_mode_config_handler(pCliEnv, pParams, pAuxBuf);
#endif

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_traffic_statistic(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_config_traffic_statistic_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_trap_add(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_config_trap_add_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_trap_delete(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_config_trap_delete_handler(pCliEnv, pParams, pAuxBuf);
    
	return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_trap_enable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_config_trap_enable_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_trap_no_enable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_config_trap_no_enable_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_trap_server_mac(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_config_trap_server_mac_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_config_trap_show(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_config_trap_show_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
RCC_EXEC_UserAccess(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    sbyte       *pVal1 = NULL;
    paramDescr  *pParamDescr1;
    sbyte       *pVal2 = NULL;
    paramDescr  *pParamDescr2;

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "name", mConfigUserAccess_Name, &pParamDescr1 );
    if ( OK != status )
    {
		return(status);
    } else pVal1 = (sbyte*)(pParamDescr1->pValue);

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "access", mConfigUserAccess_Access, &pParamDescr2 );
    if ( OK != status )
    {
		return(status);
    } else pVal2 = (sbyte*)(pParamDescr2->pValue);

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
RCC_EXEC_UserAdd(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    sbyte       *pVal1 = NULL;
    paramDescr  *pParamDescr1;
    sbyte       *pVal2 = NULL;
    paramDescr  *pParamDescr2;

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "name", mConfigUserAdd_Name, &pParamDescr1 );
    if ( OK != status )
    {
		return(status);
    } else pVal1 = (sbyte*)(pParamDescr1->pValue);

    /* get optional parameter */
    if (OK == RCC_DB_RetrieveParam(pParams, "access", mConfigUserAdd_Access, &pParamDescr2 ))
    {
        pVal2 = (sbyte*)(pParamDescr2->pValue);
    }

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
RCC_EXEC_UserDelete(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    sbyte       *pVal = NULL;
    paramDescr  *pParamDescr;

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, "name", mConfigUserDelete_Name, &pParamDescr );
    if ( OK != status )
    {
		return(status);
    } else pVal = (sbyte*)(pParamDescr->pValue);

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
RCC_EXEC_UserPassword(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    sbyte       *pVal = NULL;
    paramDescr  *pParamDescr;

    /* get required parameter */
    status = RCC_DB_RetrieveParam(pParams, NULL, mConfigUserPassword_NULL1, &pParamDescr );
    if ( OK != status )
    {
		return(status);
    } else pVal = (sbyte*)(pParamDescr->pValue);

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
RCC_EXEC_UserShow(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_diag(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_diag_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_eeprom_clear(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_eeprom_clear_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_eeprom_dump(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_eeprom_dump_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_eeprom_format(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_eeprom_format_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_eeprom_test(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_eeprom_test_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_login(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_login_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_module(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_module_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_obring_disable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_obring_disable_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_obring_enable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_obring_enable_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_obring_reboot(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_obring_reboot_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_switch_getreg(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_switch_getreg_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_debug_switch_setreg(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_debug_switch_setreg_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_enable(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
	status = cli_exec_enable_handler(pCliEnv, pParams, pAuxBuf);
    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_exit(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
#if 1
    RLSTATUS status = OK;

    status = cli_exec_exit_handler(pCliEnv, pParams, pAuxBuf);

    return status;
#else
    sbyte       *pVal = NULL;
    paramDescr  *pParamDescr;

    /* get optional parameter */
    if (OK == RCC_DB_RetrieveParam((struct paramList*) pParams, "all", mExit_All, &pParamDescr ))
    {
        pVal = (sbyte*)(pParamDescr->pValue);
    }

    return (NULL == pVal ? STATUS_RCC_EXIT : STATUS_RCC_EXIT_ALL);
#endif
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
RCC_EXEC_Help(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    return RCC_HELP_RetrieveHelp(pCliEnv, NULL, FALSE);
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
RCC_EXEC_HelpEdit(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    return RCC_HELP_EditHelp(pCliEnv);
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
RCC_EXEC_HelpGlobals(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RCC_HELP_Globals(pCliEnv);
    return OK;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_history(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    return RCC_HIST_DispHistBuff(pCliEnv);
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_ping(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_exec_ping_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_reset(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_exec_reset_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_signal(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

#if MODULE_SIGNALE
    status  = cli_show_signal_handler(pCliEnv, pParams, pAuxBuf);
#endif
    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_counters(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_counters_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_device(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_device_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_mac_addr_table(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
	status = cli_show_mac_addr_table_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_memory(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_memory_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_obring(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_obring_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_obring_topo(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_obring_topo_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_port_config(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_port_config_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_port_neigbor(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_port_neigbor_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_port_status(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_port_status_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_port_traffic(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_port_traffic_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_priority_queue_map(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
    status  = cli_show_priority_queue_map_handler(pCliEnv, pParams, pAuxBuf);
    
   return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_qos_set(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    /* TO DO: Add your handler code here */
    status = cli_show_qos_set(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_register(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;
    
    status = cli_show_register_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}



/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_system(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_system_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_task(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_show_task_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_task_runtime(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_task_runtime_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_uart(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

#if MODULE_UART_SERVER
	status = cli_show_uart_handler(pCliEnv, pParams, pAuxBuf);
#endif
    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_show_version(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_version_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_show_vlan(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

    status = cli_show_vlan_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_tftp(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    RLSTATUS    status = OK;

	status = cli_exec_tftp_handler(pCliEnv, pParams, pAuxBuf);

    return status;
}

/*-----------------------------------------------------------------------------------*/

extern RLSTATUS 
rcc_exec_tree(cli_env *pCliEnv, paramList *pParams, sbyte *pAuxBuf)
{
    cmdNode     *pNode = RCC_DB_GetCommandNode(pCliEnv);
    sbyte       *pVal  = NULL;
    paramDescr  *pParamDescr;
    ubyte4       flags = 0;

    /* get optional parameter */
    if (OK == RCC_DB_RetrieveParam(pParams, "-syntax", mTree__syntax, &pParamDescr ))
        flags = kTREE_FLAG_SYNTAX;

    if (NULL == pNode)
        pNode = MMISC_GetCurrRoot(pCliEnv);

    if (FLAG_SET(pNode, kRCC_COMMAND_META))
        pNode = RCC_DB_GetParentNode(pCliEnv, pNode);

    RCC_DB_ShowTree(pCliEnv, pNode, 0, 0, flags);

    return OK;
}

